### PR TITLE
🛠️ fix `detections_to_tensor`

### PR DESCRIPTION
**Pull request by SkalskiP**
# Description

Fix for https://github.com/roboflow/supervision/issues/215

## Type of change

Please delete options that are not relevant.

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] This change requires a documentation update

## How has this change been tested, please provide a testcase or example of how you tested the change?

- New unit tests
- Manual tests in google Colab: https://colab.research.google.com/drive/1WMFkOnapd4DOXGeb7B4xcGl3SDvWCTQQ?usp=sharing

## Any specific deployment considerations

Nope.

## Docs

-   [ ] Docs updated? What were the changes:

### CODE REVIEW

**Comment by SkalskiP** [comment]
@hardikdava take a look if you'll have time. I tested with your failure example and it works as expected!

**Comment by hardikdava** [comment]
hey @SkalskiP :wave: , thanks for fixing the issue and sharing colab. I tested and it is fixed. You can merge it.

**Comment by hardikdava** [comment]
Can you also take a look at #212? I think that is simple bug.

**Comment by SkalskiP** [comment]
> Can you also take a look at #212? I think that is simple bug.

I will submit a fix for it later today. It is a simple bug as well. 

We are merging and closing #215.

**Pull request merged**
