### PR TITLE
ci: 🚧 github action - python cache added 🚀

### PR DESCRIPTION
**Pull request by onuralpszr**

### CODE REVIEW

**Comment by SkalskiP** [comment]
@onuralpszr, what's happening here? 🤔💭

**Comment by onuralpszr** [comment]
> @onuralpszr, what's happening here? 🤔💭

I am setting python cache for skip install all together because we don't need to install reqs everytime and reduce github action time more

**Comment by onuralpszr** [comment]
You can see from here I got the caches : https://github.com/roboflow/supervision/actions/caches

**Comment by onuralpszr** [comment]
@SkalskiP this is ready for merge and but I wanna try clear-cache action but it needs to be merge first to try it.

**Comment by SkalskiP** [comment]
Will we need to change that: `.github/requirements-dev.txt` every time we update our dependencies?

**Comment by onuralpszr** [comment]
> Will we need to change that: `.github/requirements-dev.txt` every time we update our dependencies?

it is a generated via poetry so we don't have to do manually too crazy work. It just a file for checking our deps are fine. so it is semi-automatic, file generated by poetry but file send by us.

**Comment by onuralpszr** [comment]
Command I issued

poetry export --without-hashes -f requirements.txt -o .github/requirements-dev.txt

I just added "pytest" manually for sake of do tests. Rest of them automatic.

**Comment by SkalskiP** [comment]
> Command I issued
> 
> ```
> poetry export --without-hashes -f requirements.txt -o .github/requirements-dev.txt
> ```
> 
> I just added "pytest" manually for sake of do tests. Rest of them automatic.

So in case we will update our deps, all we need to do is run this command?

**Comment by onuralpszr** [comment]
> > Command I issued
> > ```
> > poetry export --without-hashes -f requirements.txt -o .github/requirements-dev.txt
> > ```
> > 
> > 
> > I just added "pytest" manually for sake of do tests. Rest of them automatic.
> 
> So in case we will update our deps, all we need to do is run this command?

Yes and add pytest that is it. Simple

**Comment by SkalskiP** [comment]
Okey, @onuralpszr so we need to merge it to so you can test if it works properly?

**Comment by onuralpszr** [comment]
> Okey, @onuralpszr so we need to merge it to so you can test if it works properly?

For clear-cache yes I need this to be merge.

**Comment by onuralpszr** [comment]
> > Okey, @onuralpszr so we need to merge it to so you can test if it works properly?
> 
> For clear-cache yes I need this to be merge.

Cache test itself works. I can already see in action it was caching it.

**Review by SkalskiP — APPROVED** [review]

**Comment by SkalskiP** [comment]
Merging :)

**Comment by onuralpszr** [comment]
@SkalskiP cache clear test worked perfectly.

**Comment by onuralpszr** [comment]
Related manual test : https://github.com/roboflow/supervision/actions/runs/6495674782

**Pull request merged**
