### PR TITLE
Detections to encoded json dict

### PR DESCRIPTION
**Pull request by hardikdava**
# Description

This can be very useful for json communication. Generally numpy array has to be encode for json communication. This functionality is very useful for REST api communication, MQTT, kafka communication. This implementation made this communication very simple by extending functionality of Detections class. 

## Type of change

-   [x] New feature (non-breaking change which adds functionality)
-   [x] This change requires a documentation update

## How has this change been tested, please provide a testcase or example of how you tested the change?

Tested locally. 

## Docs

-   [ ] Docs updated? What were the changes:

### CODE REVIEW

**Comment by SkalskiP** [comment]
Hi @hardikdava 👋🏻 Why you decided to close the issue?

**Comment by hardikdava** [comment]
Hey @SkalskiP  👋🏻, I tested with MQTT client base and my implementation was returning encoded strings which was intended but naming should be improved. But then I decided to close this and implement full-proof function for converting detections to encoded strings and loading detections from encoded strings. I believe this will be really helpful for fronted-backend communication as well as for micro-services architecture. 

Just a side note, I can help contributing as roadmap if there is. Feel free to contact me.

**Comment by SkalskiP** [comment]
Hi, @hardikdava understood. I can't wait for v2 of this PR. As for help with development, we plan to put a lot of work into benchmarking capabilities. But we are still working on scoping the problem. In the meantime, would you like to add loading and saving logic for the COCO dataset format?

**Comment by hardikdava** [comment]
Hey @SkalskiP , understood. I can work on Coco data loading and saving implementation. Is there any issue created for this? On a sidenote of benchmarking please checkout `torchmetrics`. It has lot of capabilities for benchmarking for various tasks.

**Comment by hardikdava** [comment]
@SkalskiP I have already made some progress for coco dataset import and export. Object Detections are supported now. I am still working on instance segmentation dataset format.

**Pull request closed without merging**
