### PR TITLE
build(deps): 🚀 min and max supervision package requirements are added

### PR DESCRIPTION
**Pull request by onuralpszr**

### CODE REVIEW

**Comment by onuralpszr** [comment]
@SkalskiP  I did not lowered extreme but try keep in reason and also check other deps but I only focused on "requirements" for development I assume you have proper machine can install latest dev tools and packages

**Comment by SkalskiP** [comment]
Hi @onuralpszr 👋🏻 Have you perhaps had a chance to test supervision with minimal dependencies?

**Comment by onuralpszr** [comment]
@SkalskiP I fix the py12 version control so instead of merge py12 PR I can configure versions for py12 in here and that will set  our max version of python to python 3.12 and latest version of packages.

**Comment by SkalskiP** [comment]
@onuralpszr, there is a conflict in `poetry.lock`. Could you take a look?

**Comment by onuralpszr** [comment]
> @onuralpszr, there is a conflict in `poetry.lock`. Could you take a look? 

I am fixing it okay

**Comment by onuralpszr** [comment]
@SkalskiP conflict solved.

**Review by SkalskiP — APPROVED** [review]

**Comment by SkalskiP** [comment]
Thanks a lot, @onuralpszr 🙏🏻 Let's test it out! Merging.

**Pull request merged**
