### PR TITLE
Remove class list dependency for roboflow to detection conversion

### PR DESCRIPTION
**Pull request by akashAD98**
remoed class_list arg from core.py file

# Description

No need to ask user for providing  `class_list`
simplify the [sv.Detections.from_roboflow](https://supervision.roboflow.com/detection/core/#supervision.detection.core.Detections.from_roboflow) API and remove extra argument.

solved this issue : https://github.com/roboflow/supervision/issues/394

Please delete options that are not relevant.
-   [ x] New feature (non-breaking change which adds functionality)
-   [ x] This change requires a documentation update

## Docs

-   [ ] Docs updated? What were the changes:
- once this is perfect ill update docs

### CODE REVIEW

**Comment by hardikdava** [comment]
Hi @akashAD98 👋 , thank you for contributing to `Supervision`. I would suggest you to following things first.

- Accept and sign CLA.
- Please read carefully about contributing guideline [here](https://github.com/roboflow/supervision/blob/develop/CONTRIBUTING.md)
- Attach minimal python code or colab notebook to reproduce your results or bugs.

**Comment by hardikdava** [comment]
@SkalskiP @capjamesg This might generate conflicts in roboflow server. Please have a look.

**Comment by hardikdava** [comment]
@akashAD98 I have fixed class id conversion bug.

**Comment by hardikdava** [comment]
@SkalskiP If we want to accept this PR then please fix the tests.

**Comment by SkalskiP** [comment]
Hi, @akashAD98 👋🏻! Could you accept the CLA?

**Comment by akashAD98** [comment]
@hardikdava i accepted the CLA

**Comment by SkalskiP** [comment]
@akashAD98 and @hardikdava, I fixed the tests and tested it on example [roboflow/inference](https://github.com/roboflow/inference) result, and everything looks fine. We can merge!

**Review by SkalskiP — APPROVED** [review]

**Comment by akashAD98** [comment]
thanks @SkalskiP

**Comment by SkalskiP** [comment]
@akashAD98, thanks for help!

**Pull request merged**
