### PR TITLE
ci(pypi): 🚧 test(a,b,rc) release to pypi github action added

### PR DESCRIPTION
**Pull request by onuralpszr**
# Description
 
Alpha,beta,release release candidate type of release github action added.

https://peps.python.org/pep-0440/#public-version-identifiers

### CODE REVIEW

**Comment by SkalskiP** [comment]
@onuralpszr, how would we use it? 🤔 💭

**Comment by onuralpszr** [comment]
Usage:

I assume everything is ready for release 

Example test release:

Let's say we want to release first alpha and release is "v0.17.0a1"

You change your toml file version to "0.17.0a1" 

```bash
git tag v0.17.0a1
git push --tags origin 
```

CI will do magic and release to pypi that's all.

**Comment by onuralpszr** [comment]
> @onuralpszr
> 
> * Do I make the tag on `develop` or `main`?
> * How is that different from a regular release? Looks like I could in theory just as well release with this method. Am I wrong?

You can tag both (develop or main) or I can disable one If you like no problem, and no difference from regular release it just all alpha,beta,rc I did 2 CI because of "rules" rest of them are same.

**Comment by onuralpszr** [comment]
> @onuralpszr, let's merge it and see how it works! I guess you need my `PYPI_USERNAME`, `PYPI_PASSWORD` and `PYPI_TEST_PASSWORD` environment variables?

As a secret yes please add them next time we can convert to api key (better solution) but before add please if there exiting secrets if yes no need to add (I assume those secrets are correct)

**Comment by onuralpszr** [comment]
> @onuralpszr, can we make it `PYPI_USERNAME`, `PYPI_PASSWORD`, `PYPI_TEST_USERNAME` and `PYPI_TEST_PASSWORD`? I'm using `username: __token__` on pypi.  

Yes we can do it. Let me do it (travel coding time 😀 )

**Comment by onuralpszr** [comment]
@SkalskiP  all done. Let's see and try to release a beta as "b0"

**Comment by SkalskiP** [comment]
@onuralpszr, one more thing I need to ask. How is the version of the package resolved? If the version in `pyproject.toml` is `0.14.0` and I use `0.14.0b1` tag. Which version will be used as a package version in PyPI?

**Comment by onuralpszr** [comment]
@SkalskiP  I just notice you don't use "v" in tagging... hmmm let me change that without "v" If you like ?

**Comment by SkalskiP** [comment]
@onuralpszr do we need that `v`? All our git tags didn't used `v`, I really wouldn't want to break that naming convention now :/

**Comment by onuralpszr** [comment]
@SkalskiP I removed it.

**Review by SkalskiP — APPROVED** [review]

**Comment by SkalskiP** [comment]
Merging! And let's test if build and publish works.

**Comment by onuralpszr** [comment]
@SkalskiP  once you tag show will start hopefully :)

**Pull request merged**
