### PR TITLE
Create sv.BlurAnnotator #395

### PR DESCRIPTION
**Pull request by Rajarshi-Misra**
# Description

Created sv.BlurAnnotator. The code contain a BlurAnnotator class which contains function to blur annotate the detections.

## Type of change

-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] This change requires a documentation update

## How has this change been tested, please provide a testcase or example of how you tested the change?

YOUR_ANSWER

## Any specific deployment considerations

The docs might require update due to the new annotator class

## Docs

-   [ ] Docs updated? What were the changes:

### CODE REVIEW

**Comment by hardikdava** [comment]
@Rajarshi-Misra Please accept and sign CLA so we can start review it. Please update description of PR and link related issues.

**Comment by SkalskiP** [comment]
Hi, @Rajarshi-Misra! 👋🏻 Thanks a lot for your interest in supervision! 🔥 

We try to make annotators accessible for users like this:

```python
import supervision as sv

blur_annotator = sv.BlurAnnotator()
```

To make this happen you need to add an import of `BlurAnnotator` in the main file `__init__.py`. Try to locate this import:

```python
from supervision.annotators.core import (
    BoundingBoxAnnotator,
    BoxCornerAnnotator,
    CircleAnnotator,
    EllipseAnnotator,
    LabelAnnotator,
    MaskAnnotator,
    TraceAnnotator,
)
```

And make it:

```python
from supervision.annotators.core import (
    BoundingBoxAnnotator,
    BoxCornerAnnotator,
    BlurAnnotator,
    CircleAnnotator,
    EllipseAnnotator,
    LabelAnnotator,
    MaskAnnotator,
    TraceAnnotator,
)
```

**Comment by SkalskiP** [comment]
@Rajarshi-Misra I also encountered this error when I tried to run `BlurAnnotator`:

```
error: OpenCV(4.8.0) :-1: error: (-5:Bad argument) in function 'GaussianBlur'
> Overload resolution failed:
>  - GaussianBlur() missing required argument 'src' (pos 1)
>  - GaussianBlur() missing required argument 'src' (pos 1)
```

Take a look at this colab: https://colab.research.google.com/drive/1GuG1yiiiw5knJOy-fhuGkhtjqLNkjMvE?usp=sharing

**Comment by Rajarshi-Misra** [comment]
I'll resolve the error as soon as possible

**Comment by Rajarshi-Misra** [comment]
@SkalskiP I've resolved the issue and committed to the branch. This is a result for your reference.
image

**Review by SkalskiP — APPROVED** [review]

**Comment by SkalskiP** [comment]
@Rajarshi-Misra and @hardikdava, awesome work! I'll include it in our release tomorrow! 🔥

**Comment by SkalskiP** [comment]
@Rajarshi-Misra, I want to include you in the release social media post tomorrow. Could out lin here your LinkedIn and Twitter?

**Comment by Rajarshi-Misra** [comment]
Twitter: @rajistalking
LinkedIn: https://www.linkedin.com/in/rajarshi-misra-b1142a1b7?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app

**Pull request merged**
