### PR TITLE
Fixed TraceAnnotator to respect the postion argument.

### PR DESCRIPTION
**Pull request by abhishek7kalra**
# Description

Added necessary logic in TraceAnnotator so that it now respects the position argument. The update now allows all the predefined positions which when passed to modify the tracing position.

Issue: https://github.com/roboflow/supervision/issues/420

## Type of change

Please delete options that are not relevant.

-   [x] New feature (non-breaking change which adds functionality)

## How has this change been tested, please provide a testcase or example of how you tested the change?

`trace_annotator = sv.TraceAnnotator(position=Position.TOP_LEFT)`

https://github.com/roboflow/supervision/assets/33096608/89c53f78-c5b3-413e-9d24-f74aef387265

### CODE REVIEW

**Comment by abhishek7kalra** [comment]
@SkalskiP Please review this pr.

**Comment by SkalskiP** [comment]
Hi, @abhishek7kalra! 👋🏻 Thanks for your interest in Supervision and solving this issue. 

However, the solution for this bug is much simpler. The logic that you made is already part of [`sv.Detections.get_anchors_coordinates`](https://supervision.roboflow.com/detection/core/#supervision.detection.core.Detections.get_anchors_coordinates) method. That method is called inside [`Trace`](https://github.com/roboflow/supervision/blob/145313ab8f2c0cc3e6877b6d5fc88d09d559e416/supervision/annotators/utils.py#L105) class. The problem is that the `position` argument is not being passed to the `Trace` [constructor](https://github.com/roboflow/supervision/blob/145313ab8f2c0cc3e6877b6d5fc88d09d559e416/supervision/annotators/core.py#L1034). 

All you have to do is pass `position here, and it should work.

`self.trace = Trace(max_size=trace_length, anchor=position)`

**Comment by SkalskiP** [comment]
Hi, @abhishek7kalra! 👋🏻 Unfortunately, I couldn't wait any longer for you to implement the fixes, so I decided to do it myself. Thanks a lot for your help! 🙏🏻 Merging!

**Review by SkalskiP — APPROVED** [review]

**Comment by abhishek7kalra** [comment]
Hey @SkalskiP, thank you for going ahead with the fix. I got super busy, so couldn't do the implementation myself. 😅

**Pull request merged**
