### PR TITLE
feat: ✨ Python 3.12 support added

### PR DESCRIPTION
**Pull request by onuralpszr**
### Description

Python3.12 support added for Supervision
Github actions are updated accordingly  

You should able to install via `pip install . ` or `poetry install` for development

## Any specific deployment considerations

For example, documentation changes, usability, usage/costs, secrets, etc.

## Docs

-   [X] Docs updated? What were the changes:

Python 3.12 support added into docs and readme

### CODE REVIEW

**Comment by onuralpszr** [comment]
Notes about versioning reasons


https://github.com/numpy/numpy/releases/tag/v1.24.4 

```
NumPy 1.24.4 is a maintenance release that fixes a few bugs
discovered after the 1.24.3 release. It is the last planned
release in the 1.24.x cycle. The Python versions supported by
this release are 3.8-3.11.
```

https://github.com/numpy/numpy/releases/tag/v1.25.2

```
NumPy 1.25.2 is a maintenance release that fixes bugs and regressions
discovered after the 1.25.1 release. This is the last planned release in
the 1.25.x series, the next release will be 1.26.0, which will use the
meson build system and support Python 3.12. The Python versions
supported by this release are 3.9-3.11.
```

https://github.com/scipy/scipy/releases/tag/v1.11.0

```
This release requires Python 3.9+ and NumPy 1.21.6 or greater.
For running on PyPy, PyPy3 6.0+ is required.
```

**Comment by onuralpszr** [comment]
Okay let's merge and test in RC as well

**Comment by SkalskiP** [comment]
RC is up https://pypi.org/project/supervision/0.17.1rc1/

**Comment by sanmai-NL** [comment]
In reply to https://github.com/roboflow/supervision/pull/658#issuecomment-1846786099:
The rc version works for me, using PDM and Python 3.11 on MacOS.

**Pull request merged**
