### PR TITLE
Fix yolo dataset background instance loading

### PR DESCRIPTION
**Pull request by hardikdava**
# Description

## Type of change

Please delete options that are not relevant.

-   [x] Bug fix (non-breaking change which fixes an issue)

## How has this change been tested, please provide a testcase or example of how you tested the change?

Load `coco128` dataset which contains images but not annotations. This represents background image. `Supervision` is eliminating such cases.

### CODE REVIEW

**Comment by SkalskiP** [comment]
@hardikdava, let me know when you'll be ready for review here.

**Comment by hardikdava** [comment]
@SkalskiP the fix is added. Please review it and merge it.

**Comment by SkalskiP** [comment]
@hardikdava I'm testing now. If I understand correctly, before that change, `coco128.yaml` should load only 126 entries, and after, we should have 128.

**Comment by hardikdava** [comment]
> @hardikdava I'm testing now. If I understand correctly, before that change, `coco128.yaml` should load only 126 entries, and after, we should have 128.

Yeah, 128 is expected result.

**Comment by SkalskiP** [comment]
@hardikdava tested! Merging.

**Pull request merged**
