### PR TITLE
Slicer for small object detection

### PR DESCRIPTION
**Pull request by hardikdava**
# Description

This PR is implementation of #250 

## Type of change

Please delete options that are not relevant.

-   [x] New feature (non-breaking change which adds functionality)
-   [x] This change requires a documentation update

## How has this change been tested, please provide a testcase or example of how you tested the change?

Google colab link:  https://colab.research.google.com/drive/1RNvsVWpkklUMZy5cjRs9y5yzBSHU9KRi?usp=sharing

## Docs

-   [x] Docs updated? What were the changes: `docs/supervision/detection/tools/slicer.md`

### CODE REVIEW

**Comment by SkalskiP** [comment]
Hi @hardikdava 👋🏻 Is it ready for review?

**Comment by hardikdava** [comment]
@SkalskiP Yeah, it is ready for review.

**Comment by SkalskiP** [comment]
@hardikdava I tried to run [Notebook](https://colab.research.google.com/drive/1RNvsVWpkklUMZy5cjRs9y5yzBSHU9KRi?usp=sharing) but it crashed. Is it up to date?

**Comment by hardikdava** [comment]
@SkalskiP Ohh, it is an issue of image downloading.

**Comment by hardikdava** [comment]
bird (2)

@SkalskiP Can you manually upload this image for testing? It should work. I just tested it.

**Comment by onuralpszr** [comment]
@SkalskiP @hardikdava 

raw URL for good for wget : https://raw.githubusercontent.com/spmallick/learnopencv/master/Exploring-Slicing-Aided-Hyper-Inference/test_images/bird.jpg

**Comment by hardikdava** [comment]
@SkalskiP It is updated now!, it is working. Thanks @onuralpszr

**Comment by onuralpszr** [comment]
> @SkalskiP It is updated now!, it is working. Thanks @onuralpszr

You're welcome :)  I am glad to help

**Comment by SkalskiP** [comment]
Hi @hardikdava 👋🏻 I'd add some unit tests to this PR. I can do that if ou don't have time.

**Comment by hardikdava** [comment]
@SkalskiP Thanks for covering some tasks for me.

**Comment by SkalskiP** [comment]
@hardikdava can I only ask one question? Why is `_offset_generation` producing offsets with 4 coordinates and not just two? I would assume we could move boxes with just `x` and `y` vectors.

**Comment by SkalskiP** [comment]
I'll try to do some minor changes when I'll be working on tests.

**Comment by SkalskiP** [comment]
@hardikdava slicer looks fantastic! 

https://github.com/roboflow/supervision/assets/26109316/1551cdd0-c493-43e2-8819-79d98149713f

**Comment by hardikdava** [comment]
Looks really Amazing :)

**Review by SkalskiP — APPROVED** [review]

**Pull request merged**
