### PR TITLE
Feature FPS meaure

### PR DESCRIPTION
**Pull request by hardikdava**
# Description

This PR is for #255.

Testing colab: https://colab.research.google.com/drive/10dddDCD2HzzIBhzm0Zyj9NJsW0rQD5CX?usp=sharing

## Type of change

Please delete options that are not relevant.

-   [x] New feature (non-breaking change which adds functionality)
-   [x] This change requires a documentation update

## Docs

-   [x] Docs updated? What were the changes: docs/supervision/utils/fps.md and mkdocs.yaml

### CODE REVIEW

**Comment by hardikdava** [comment]
@SkalskiP can we include this in next release? It is small but very useful feature.

**Comment by hardikdava** [comment]
@SkalskiP conflicts are resolved. You can take a look.

**Review by onuralpszr — APPROVED** [review]

**Comment by onuralpszr** [comment]
@SkalskiP  @hardikdava  if all good I am merging this one as well.

**Comment by hardikdava** [comment]
@onuralpszr Feel free to merge it.

**Pull request merged**
