### PR TITLE
Dataset merge

### PR DESCRIPTION
**Pull request by hardikdava**
# Description

Related issue: #155

## Type of change

Please delete options that are not relevant.

-   [x] New feature (non-breaking change which adds functionality)
-   [x] This change requires a documentation update

## Any specific deployment considerations

- Documentaion needs to change
- Check docstrings

## Docs

-   [ ] Docs updated? What were the changes:

### CODE REVIEW

**Comment by hardikdava** [comment]
@SkalskiP Please try to fix if needed. I will check them tomorrow.

**Comment by SkalskiP** [comment]
@hardikdava I'll take a look in 30 min

**Review by SkalskiP — APPROVED** [review]

**Comment by SkalskiP** [comment]
@hardikdava I did a review and minor refactoring and added many unit tests. I'll test if it works on a few examples now.

**Comment by SkalskiP** [comment]
@hardikdava Tested! It looks like it works! 🔥 Merging!

**Comment by SkalskiP** [comment]
@hardikdava wanna contribute anything more? or taking a break? :D

**Comment by hardikdava** [comment]
@SkalskiP I can keep continue contributing but i can spend a bit low time. Let me know what you have in mind for further ?

**Comment by SkalskiP** [comment]
@hardikdava, how about this: https://github.com/roboflow/supervision/issues/160? This should be simple to implement.

**Pull request merged**
