### PR TITLE
WIP - feat: introduce pyproject.toml and pre-commit file

### PR DESCRIPTION
**Pull request by onuralpszr**
# Description

feat: introduce pyproject.toml and pre-commit file
feat: toml file uses poetry as a dependency management and packaging system
feat: pre-commit added. It can be use with git hooks for checks

## Extra notes

- Latest poetry have new package check system cause issue on debugpy (debugpy people already know this so waiting for their side to fix)
- It is possible to turn off that feature so debugpy can be install properly without check
- Latest packages also force me to use higher version of python so I may need to reduce this version bit more and flexible on versions 

I also found that some of the lines pass way more than 88 lines and there is no new line at the end of line in files. I did not add those changes yet but I can do if it is gets accepted. 

While I was doing migration work, I also want to hear your opinion as well, please let me know and thank you. 

List any dependencies that are required for this change.

## Type of change

-   [x] New feature (non-breaking change which adds functionality)

## How has this change been tested, please provide a testcase or example of how you tested the change?

Install poetry and run 

```
poetry install
pre-commit run --all-files
```
## Any specific deployment considerations

For example, documentation changes, usability, usage/costs, secrets, etc.

pre-commit config required on repository settings for automatic pre-commit pr and and pre-commit github actions

### CODE REVIEW

**Comment by SkalskiP** [comment]
Hi, @onuralpszr 👋🏻! I underestimated you. Thank you very much for taking the time. This was the first time I would use this setup so on this occasion I have some questions.

## Questions

1. What is the upside of `pyproject.toml` over `setup.py`?
2. What is the upside of `poetry` over `pip`?
3. Can we use `pre-commit` with the current project configuration? Namely without migrating to `poetry`?

## Notes 

> Latest packages also force me to use higher version of python so I may need to reduce this version bit more and flexible on versions

We really would like to keep the current Python version requirement. Problem is that very Computer Vision projects are slow when it comes to adopting new versions.

> I also found that some of the lines pass way more than 88 lines and there is no new line at the end of line in files.

Was that actually code or comments?

**Comment by onuralpszr** [comment]
> Hi, @onuralpszr 👋🏻! Sorry, I get distracted by other important stuff. Still, want to contribute? I hope 🙏🏻

Yes I want to do it. I answered your questions so please let me know  how do you want to proceed it.know. So I can do more work on it. I stopped a bit because of your questions.

**Comment by onuralpszr** [comment]
I am closing this PR in favor of the following PR: https://github.com/roboflow/supervision/pull/180. I will introduce pre-commit in a separate PR.

cc @SkalskiP

**Comment by SkalskiP** [comment]
Awesome @onuralpszr! 🔥 I got a bit overwhelmed with open issues and PRs before the `supervision-0.12.0` release. So anything we don't use and can close, makes me happy.

**Pull request closed without merging**
