### PR TITLE
ci: 👷 check notebook and automatically create colab link and show better difference in reviewNB

### PR DESCRIPTION
**Pull request by onuralpszr**
Idea : Any of our pull request has notebook edit or create change(s) we can review easily with single click with colab or reviewnb (login required)

### CODE REVIEW

**Comment by onuralpszr** [comment]
Example PR: https://github.com/onuralpszr/supervision/pull/135

**Comment by LinasKo** [comment]
We discussed with Piotr and think it's an improvement to the current process.

I've requested authorization internally, for this to be added into `supervision`.

One thing you mentioned afterwards is:
> Btw Can you guys add into Review NB account ?
> you can do without but too If you add you can also have extra Review NB bot as well

I didn't quite get the first question - can you explain further?
Then, can this be used without the bot account? My understanding based on the GitHub action code, is that it would extract changed ipynb notebooks and show them in the **Colab** - not even in ReviewNB. So then, do we need the bot to create the ReviewNB link? Would it need extra permissions?

**Comment by onuralpszr** [comment]
> We discussed with @SkalskiP and think it's an improvement to the current process.
> 
> I've requested authorization internally, for this to be added into `supervision`.
> 
> One thing you mentioned afterwards is:
> 
> > Btw Can you guys add into Review NB account ?
> > you can do without but too If you add you can also have extra Review NB bot as well
> 
> I didn't quite get the first question - can you explain further? Then, can this be used without the bot account? My understanding based on the GitHub action code, is that it would extract changed ipynb notebooks and show them in the **Colab** - not even in ReviewNB. So then, do we need the bot to create the ReviewNB link? Would it need extra permissions?

2 ways of usage for ReviewNB is without extra permission just login and check notebook difference or If you add bot and give perm to ReviewNB you can read all in here https://www.reviewnb.com/#faq

**Comment by LinasKo** [comment]
Let's add this right after 0.22.0 release.
We'll have time to test it out without pushing the CI changes to prod.

@onuralpszr, I'm approving preemptively. If I don't merge by Wednesday, you can do it on my behalf 😉

**Review by LinasKo — APPROVED** [review]

**Comment by onuralpszr** [comment]
@LinasKo, Sure we can test after release. Thank you.

**Pull request merged**
