### PR TITLE
ci: 👷 documentation build via mike for develop tag configuration

### PR DESCRIPTION
**Pull request by onuralpszr**
# Description

This PR introduces a new continuous integration configuration for building our project documentation using mike. The change is implemented in the docs.yml GitHub Actions workflow file. The motivation for this change is to automate the process of generating and deploying our documentation for the develop branch. This will ensure that our documentation is always up-to-date with the latest changes in the codebase.

## Type of change

Please delete options that are not relevant.

-   [X] New feature (non-breaking change which adds functionality)
-   [X] This change requires a documentation update

## Any specific deployment considerations

No specific deployment considerations are required for this change. The GitHub Actions workflow runs in the GitHub-hosted ubuntu-latest environment and does not incur any additional costs.

## Docs

-   [X] Docs updated? The changes include an update to our CI/CD process documentation to include the new automated documentation build and deployment step.

### CODE REVIEW

**Comment by SkalskiP** [comment]
@onuralpszr, is this ready to go?

**Comment by onuralpszr** [comment]
> @onuralpszr, is this ready to go? 

Testing one more thing then i will tell you to go merge it

**Comment by SkalskiP** [comment]
@onuralpszr awesome! Let me know once you'll be ready.

**Comment by onuralpszr** [comment]
@SkalskiP  merge it.

**Review by SkalskiP — APPROVED** [review]

**Comment by SkalskiP** [comment]
Merged! Now it's time to test it 🔥

**Pull request merged**
