### PR TITLE
file utilities ret-type updated and extended function to work with Pathlib

### PR DESCRIPTION
**Pull request by hardikdava**
# Description

- This PR will expose some file read/write utilities function for easy to use.
- File input can now support Path or string

List any dependencies that are required for this change.

## Type of change

Please delete options that are not relevant.

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] This change requires a documentation update

## How has this change been tested, please provide a testcase or example of how you tested the change?

YOUR_ANSWER

## Any specific deployment considerations

For example, documentation changes, usability, usage/costs, secrets, etc.

## Docs

-   [x] Docs updated? What were the changes: docstrings updated

### CODE REVIEW

**Comment by LinasKo** [comment]
Hi @hardikdava 👋 

Good to see you back in supervision! Piotr mentioned your early contributions, and I've seen a few tickets myself.

I like the expanded `pathlib` support, but have some doubts about exposing text methods publicly.
I'm worried these methods will be detached from `supervision`. Here's what I mean:

Let's pick 'read_yaml_file'. I believe it should be publicly exposed only if it allows users to format some data in a way where it would be used by another `supervision` method, and supervision does not already have a solution for that.

Do you foresee or already have such a use case?

Otherwise, if it's a standalone yet opinionated convenience method unrelated to computer vision, and I don't think we should expose those in global scope.

**Comment by LinasKo** [comment]
Hey @hardikdava ,

Great to see the reasoning.

I feel neutral about it, so let's take the option that lets us move forward. Let's not change which methods are exposed publicly for now.

After we merge other changes, I commit to speaking with @SkalskiP to see his viewpoint  - essentially why these methods weren't public to begin with.

That should happen in about a week, but feel free to ping me if it doesn't :wink:

**Comment by hardikdava** [comment]
@LinasKo Fair enough. I will update the PR.

**Comment by LinasKo** [comment]
Did some basic testing - looks good.

<details>
  <summary>Code</summary>
  
  ```python
  from supervision.utils.file import read_json_file, save_json_file, read_txt_file, save_text_file, read_yaml_file, save_yaml_file
  from pathlib import Path


  if __name__ == "__main__":
      # Empty file - string path
      save_json_file(file_path="empty.json", data={})
      save_yaml_file(file_path="empty.yaml", data={})
      save_text_file(lines=[], file_path="empty.txt")
  
      assert read_json_file(file_path="empty.json") == {}
      assert read_yaml_file(file_path="empty.yaml") == {}
      assert read_txt_file(file_path="empty.txt") == []
  
      # Empty paths
      save_json_file(file_path=Path("empty.json"), data={})
      save_yaml_file(file_path=Path("empty.yaml"), data={})
      save_text_file(lines=[], file_path=Path("empty.txt"))
  
      assert read_json_file(file_path=Path("empty.json")) == {}
      assert read_yaml_file(file_path=Path("empty.yaml")) == {}
      assert read_txt_file(file_path=Path("empty.txt")) == []
  
      # Write and read
      data_list = ["some", "data", "list"]
      data_dict = {"some": "data", "dict": "here"}
  
      save_json_file(file_path="data.json", data=data_dict)
      save_yaml_file(file_path="data.yaml", data=data_dict)
      save_text_file(lines=data_list, file_path="data.txt")
  
      assert read_json_file(file_path="data.json") == data_dict
      assert read_yaml_file(file_path="data.yaml") == data_dict
      assert read_txt_file(file_path="data.txt") == data_list
  
      # Write and read with Path
      save_json_file(file_path=Path("data.json"), data=data_dict)
      save_yaml_file(file_path=Path("data.yaml"), data=data_dict)
      save_text_file(lines=data_list, file_path=Path("data.txt"))
  
      assert read_json_file(file_path=Path("data.json")) == data_dict
      assert read_yaml_file(file_path=Path("data.yaml")) == data_dict
      assert read_txt_file(file_path=Path("data.txt")) == data_list
  ```

</details>

**Review by LinasKo — APPROVED** [review]

**Comment by hardikdava** [comment]
@LinasKo I just found a usecase for reading json file. Currently, sv.JsonSink does not have any loading mechanism in order to work with it we need a method to load data from json file.

**Comment by LinasKo** [comment]
Hi @hardikdava,

I spoke with Piotr, and he agrees that we shouldn't publicly expose these yet for a very similar reason—they are not a significant part of the API supervision provided.

**Comment by hardikdava** [comment]
@LinasKo thanks for considering and discussing it with Piotr.

**Pull request merged**
