### PR TITLE
ci: 👷 python3.13 ci tests and tox ver added

### PR DESCRIPTION
**Pull request by onuralpszr**
# Description

Python 3.13 tests enablements

### CODE REVIEW

**Comment by onuralpszr** [comment]
Python3.13 OSX local pytest run results

```
❯ pytest test
==================================================================================================================== test session starts ====================================================================================================================
platform darwin -- Python 3.13.0, pytest-8.3.3, pluggy-1.5.0
rootdir: /Users/onuralp/supervision
configfile: pyproject.toml
collected 544 items

test/annotators/test_utils.py .........                                                                                                                                                                                                               [  1%]
test/classification/test_core.py .....                                                                                                                                                                                                                [  2%]
test/dataset/formats/test_coco.py .............................                                                                                                                                                                                       [  7%]
test/dataset/formats/test_pascal_voc.py .......                                                                                                                                                                                                       [  9%]
test/dataset/formats/test_yolo.py .......................                                                                                                                                                                                             [ 13%]
test/dataset/test_core.py ........                                                                                                                                                                                                                    [ 14%]
test/dataset/test_utils.py ......................................                                                                                                                                                                                     [ 21%]
test/detection/test_core.py .....................................................                                                                                                                                                                     [ 31%]
test/detection/test_csv.py ........                                                                                                                                                                                                                   [ 33%]
test/detection/test_json.py ....                                                                                                                                                                                                                      [ 33%]
test/detection/test_line_counter.py ................................                                                                                                                                                                                  [ 39%]
test/detection/test_lmm.py ................                                                                                                                                                                                                           [ 42%]
test/detection/test_lmm_florence_2.py ...................                                                                                                                                                                                             [ 46%]
test/detection/test_overlap_filter.py ...............................                                                                                                                                                                                 [ 51%]
test/detection/test_polygon_zone_annotator.py ..                                                                                                                                                                                                      [ 52%]
test/detection/test_polygonzone.py ......                                                                                                                                                                                                             [ 53%]
test/detection/test_utils.py .........................................................................................................                                                                                                                [ 72%]
test/detection/tools/test_inference_slicer.py ...................                                                                                                                                                                                     [ 76%]
test/draw/test_color.py ...................                                                                                                                                                                                                           [ 79%]
test/geometry/test_core.py ..................................                                                                                                                                                                                         [ 85%]
test/geometry/test_utils.py ........                                                                                                                                                                                                                  [ 87%]
test/metrics/test_detection.py ..................                                                                                                                                                                                                     [ 90%]
test/utils/test_conversion.py ........                                                                                                                                                                                                                [ 92%]
test/utils/test_file.py ......                                                                                                                                                                                                                        [ 93%]
test/utils/test_image.py ...............                                                                                                                                                                                                              [ 95%]
test/utils/test_internal.py ............                                                                                                                                                                                                              [ 98%]
test/utils/test_iterables.py ..........                                                                                                                                                                                                               [100%]

===================================================================================================================== warnings summary ======================================================================================================================
supervision/geometry/utils.py:34: 2 warnings
test/detection/test_line_counter.py: 285 warnings
test/geometry/test_utils.py: 8 warnings
  DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)

test/detection/tools/test_inference_slicer.py::test_inference_slicer_overlap[slice_wh0-overlap_ratio_wh0-None-None-exception0]
test/detection/tools/test_inference_slicer.py::test_inference_slicer_overlap[slice_wh2-overlap_ratio_wh2-None-None-exception2]
test/detection/tools/test_inference_slicer.py::test_inference_slicer_overlap[slice_wh4-overlap_ratio_wh4-overlap_wh4-expected_overlap4-exception4]
test/detection/tools/test_inference_slicer.py::test_inference_slicer_overlap[slice_wh6-overlap_ratio_wh6-None-None-exception6]
test/detection/tools/test_inference_slicer.py::test_inference_slicer_overlap[slice_wh7-overlap_ratio_wh7-None-None-exception7]
test/detection/tools/test_inference_slicer.py::test_inference_slicer_overlap[slice_wh8-overlap_ratio_wh8-None-None-exception8]
test/detection/tools/test_inference_slicer.py::test_inference_slicer_overlap[slice_wh9-overlap_ratio_wh9-overlap_wh9-None-exception9]
test/detection/tools/test_inference_slicer.py::test_inference_slicer_overlap[slice_wh11-overlap_ratio_wh11-None-None-exception11]
  SupervisionWarnings: `overlap_ratio_wh` in `InferenceSlicer.__init__` is deprecated and will be removed in `supervision-0.27.0`. Please manually set it to `None` and use `overlap_wh` instead.

test/metrics/test_detection.py::test_compute_average_precision[recall0-precision0-1.0-exception0]
test/metrics/test_detection.py::test_compute_average_precision[recall1-precision1-0.0-exception1]
test/metrics/test_detection.py::test_compute_average_precision[recall2-precision2-0.5-exception2]
test/metrics/test_detection.py::test_compute_average_precision[recall3-precision3-0.75-exception3]
  DeprecationWarning: `trapz` is deprecated. Use `trapezoid` instead, or one of the numerical integration functions in `scipy.integrate`.

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================================================================================================= 544 passed, 307 warnings in 1.30s =============================================================================================================
```

**Comment by onuralpszr** [comment]
@LinasKo If you ready lets merge in to enable tests for others as well. (I can add other distros in case If you want to be make sure)

**Comment by LinasKo** [comment]
@onuralpszr, you managed to poetry-install supervision cleanly?

I'm failing to build scipy, but it's highly likely to do with my system.

**Comment by onuralpszr** [comment]
@LinasKo I can confirm poetry issue as a "poetry issue" let's merge this CI because "pip" / pypi and CI works. and I will open new PR for poetry

**Comment by LinasKo** [comment]
In other words, this does not mean we support Python 3.13 yet.

This change adds a way to run Python 3.13 tests on the CI. We found an issue in Poetry itself, and Onuralp will handle that in a different PR.

**Review by LinasKo — APPROVED** [review]

**Pull request merged**
