### PR TITLE
Add polygon rotation functions

### PR DESCRIPTION
**Pull request by sharingan000**
# Description

I wrote two new functions and one auxiliary one, all of them are designed to rotate polygons at a certain angle, around a certain point. in the '2d' function you can rotate a polygon in a plane around a given point or around the center of the polygon. And the '3d' function performs rotation in three-dimensional space along any axis and for this reason will return 3-dimensional coordinates

## Type of change

Please delete options that are not relevant.

-   [ ] New feature (non-breaking change which adds functionality)

## How has this change been tested, please provide a testcase or example of how you tested the change?

google disk link - https://drive.google.com/file/d/1CrThP7A8cXzBbULWdneV5Eb3AOkvtq2l/view?usp=sharing
I recommend testing in Jupyter notebook

### CODE REVIEW

**Comment by LinasKo** [comment]
Hi @sharingan000 :wave:

Unfortunately, I'm tempted to close this one. The possible use cases for the end-users of Roboflow, the set of problems they can solve with this algo that would be related to what `supervision` provides (2D object detection, segmentation, annotation), isn't clear.

@SkalskiP, what's your take on this one?

**Comment by SkalskiP** [comment]
Hi @sharingan000 and @LinasKo 👋🏻 I must admit, I also can't think of any use case when we would need rotating polygons, and for this reason, I'm afraid we will have to close this PR. The only thing that comes to my mind is dataset augmentation, but at the moment, I do not plan to open such a front of work.

I see your interest in mathematical/geometrical issues. Our InferenceSlicer currently utilizes non_max_suppression to filter out redundant detections, which primarily appear on patch overlap. We are looking for solutions that, instead of removing duplicates, would merge them. Would you be interested in assisting us in this area?

**Comment by sharingan000** [comment]
> Hi @sharingan000 and @LinasKo 👋🏻 I must admit, I also can't think of any use case when we would need rotating polygons, and for this reason, I'm afraid we will have to close this PR. The only thing that comes to my mind is dataset augmentation, but at the moment, I do not plan to open such a front of work.
> 
> @sharingan000 I see your interest in mathematical/geometrical issues. Our InferenceSlicer currently utilizes non_max_suppression to filter out redundant detections, which primarily appear on patch overlap. We are looking for solutions that, instead of removing duplicates, would merge them. Would you be interested in assisting us in this area?

I would really like to help you with this, I just want to understand the problem a little better

**Comment by sharingan000** [comment]
> Hi @sharingan000 and @LinasKo 👋🏻 I must admit, I also can't think of any use case when we would need rotating polygons, and for this reason, I'm afraid we will have to close this PR. The only thing that comes to my mind is dataset augmentation, but at the moment, I do not plan to open such a front of work.
> 
> @sharingan000 I see your interest in mathematical/geometrical issues. Our InferenceSlicer currently utilizes non_max_suppression to filter out redundant detections, which primarily appear on patch overlap. We are looking for solutions that, instead of removing duplicates, would merge them. Would you be interested in assisting us in this area?

yes, I would really like to help you, I just want to know more about the problem

**Comment by LinasKo** [comment]
Small update - @SkalskiP and @sharingan000,

The contributor for #500 PR is keen to continue, so it's only the weighted fusion that we'd like to see.

Let's move further discussions to #268 - I'll post an explanation there shortly.

**Pull request closed without merging**
