### PR TITLE
Update line_counter.py

### PR DESCRIPTION
**Pull request by TommyZihao**
Add more return info in order to get more details about class_name and in/out results

# Description

Please include a summary of the change and which issue is fixed or implemented. Please also include relevant motivation and context (e.g. links, docs, tickets etc.).

List any dependencies that are required for this change.

## Type of change

Please delete options that are not relevant.

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] This change requires a documentation update

## How has this change been tested, please provide a testcase or example of how you tested the change?

YOUR_ANSWER

## Any specific deployment considerations

For example, documentation changes, usability, usage/costs, secrets, etc.

## Docs

-   [ ] Docs updated? What were the changes:

### CODE REVIEW

**Comment by SkalskiP** [comment]
Hi @TommyZihao 👋🏻! Thank you very much for your interest in our project. Could you give me a little more detail on the changes you made?

**Comment by TommyZihao** [comment]
hi, 
I want to get more infos about how many car, motocycle, bike, person, or bus crossing the line, or crossing the zone.
but native trigger function can't return these infos.
so I made this PR, 
if you have more graceful solution, looking forward to it!

**Comment by SkalskiP** [comment]
Hi @TommyZihao, we need to do a solid re-design and re-factor of `LineZone`. People tested our implementation, and it turned out that they found several problems.
- Extra counts. Objects that are passing next to the line can add to the count. You can read more about it here (https://github.com/roboflow/supervision/issues/87) and here (https://github.com/roboflow/supervision/discussions/107).
- Separate line zone counts per class. You can read more about it here (https://github.com/roboflow/supervision/issues/87).
- More customization `LineZoneAnnotator`. You can read more about it here (https://github.com/roboflow/supervision/issues/79).
- As for your problem, the plan is that the `trigger` method will return `Tuple[np.ndarray, np.ndarray]`. One `np.ndarray` will indicate whether an object with the corresponding index has crossed the line in the `in` direction. The other will do the same for `out` direction.
- Add LineZone documentation and examples. 

All in all. I'll need to take care of all of that soon to address the valid needs of the community.

**Comment by TommyZihao** [comment]
Thanks, I will read these issues.
Looking forward to new features about supervison.

**Comment by SkalskiP** [comment]
I would love to have a power user 💪💪💪 like you on board. As for `LineZone` I need to design API first. Dou you plan to use `supervision` in your projects?

**Comment by TommyZihao** [comment]
yes, I am a video blogger in China, I plan to do lots of tutorials about YOLOv8 and supervision
My video channel: https://space.bilibili.com/1900783
Looking forward to more new features about supervision

**Comment by SkalskiP** [comment]
Hi, @TommyZihao 👋🏻 We plan a major `LineCounter` redesign soon. I'm closing this PR for now.

**Pull request closed without merging**
