### PR TITLE
feat: 🛠  adding python dev tools into toml file

### PR DESCRIPTION
**Pull request by onuralpszr**
# Description

Since we move into pyproject toml, I am also adding other dev tools we used in project into toml file (linter,type checker and etc)

### CODE REVIEW

**Comment by onuralpszr** [comment]
@SkalskiP I also took the liberty to fix "action failing" problem as well.  Now all actions are properly pull requests branches and start checking.

**Comment by SkalskiP** [comment]
> I also took the liberty to fix "action failing" problem as well. Now all actions are properly pull request branches and start testing properly.

@onuralpszr, awesome! 🔥 Is that solution to https://github.com/roboflow/supervision/issues/138? 

What command do I use to install dev tools locally with poetry? 

  ```
  poetry install --extras "dev"
  ```

How do I build a package?

**Comment by onuralpszr** [comment]
> > I also took the liberty to fix "action failing" problem as well. Now all actions are properly pull request branches and start testing properly.
> 
> @onuralpszr, awesome! 🔥 Is that solution to #138?
> 
> What command do I use to install dev tools locally with poetry?
> 
> ```
> poetry install --extras "dev"
> ```
> 
> How do I build a package?

just use "poetry install" will install ALL

**Comment by onuralpszr** [comment]
@SkalskiP  also yes I fix PR problem too.

**Comment by SkalskiP** [comment]
> also yes I fix PR problem too.

@onuralpszr that's awesome!

> just use "poetry install" will install ALL If you don't want to install dev or docs you can exclude them but without any parameters it will install all of them

Wouldn't we want to separate `dev` dependencies? And not install them by default? How can I exclude it?

**Comment by onuralpszr** [comment]
> > also yes I fix PR problem too.
> 
> @onuralpszr that's awesome!
> 
> > just use "poetry install" will install ALL If you don't want to install dev or docs you can exclude them but without any parameters it will install all of them
> 
> Wouldn't we want to separate `dev` dependencies? And not install them by default? How can I exclude it?

For development you don't do that. For pip or usual install of supervision it is already separated

**Comment by onuralpszr** [comment]
To clarify bit more 

```
[tool.poetry.group.dev.dependencies]
[tool.poetry.group.docs.dependencies]
```

These poetry groups are ONLY run we do install from source via poetry without any parameter but I can also exclude them by using  

`poetry install --without dev,docs`

This will only give me main deps + supervision.

**Comment by SkalskiP** [comment]
@onuralpszr like I said in the other issue. No complains here. I just want to know how to use new tools and understand the behavior. 👍🏻

**Comment by onuralpszr** [comment]
@SkalskiP  no problem. I am glad to bring into table as well.

**Comment by onuralpszr** [comment]
@SkalskiP  also yay no more broken PR check :)

**Comment by SkalskiP** [comment]
@onuralpszr I'm so happy about it. We will finally be able to have the unit test when merging from a fork! 

I'm curious, is it possible to automate the commands below using pre-commit? 

```
isort --profile black supervision/
black supervision
```

**Comment by onuralpszr** [comment]
> @onuralpszr I'm so happy about it. We will finally be able to have the unit test when merging from a fork!
> 
> I'm curious, is it possible to automate the commands below using pre-commit?
> 
> ```
> isort --profile black supervision/
> black supervision
> ```

YESS !!! That's why I added pre-commit as well. We going to have full automate check and auto fix (if tool can do) and we going have more clean and better code structure. I am going to target python 3.8 as typing style. That's because I cannot use "python 3.10 or 3.11" only features and prevent compatibility breaks as well.

**Comment by onuralpszr** [comment]
Final idea is,  removal of all makefile and other scripts and clean up github CI and use only "pre-commit" as automation and for developers we can also easily tell them to use pre-commit and suggest them use as "git hook" so they will also in check and If they forgot well that's also no problem because our CI will catch them all.

**Comment by SkalskiP** [comment]
@onuralpszr maybe we will do it for the `supervision-0.13.0` release.

**Comment by onuralpszr** [comment]
> @onuralpszr maybe we will do it for the `supervision-0.13.0` release.

Okay, I will start working on it. We can do merge after release day.

**Pull request merged**
