### PR TITLE
Fix issue #754

### PR DESCRIPTION
**Pull request by rolson24**
# Description

### New version of this PR (https://github.com/roboflow/supervision/pull/1034) with one commit and requested changes.

This change addresses this issue: (https://github.com/roboflow/supervision/issues/754)
`update_with_detections` now returns the original detections that were tracked by ByteTrack with their original bboxes, masks, class_ids, data fields and with updated track_ids. Detections that were not tracked this frame are not included in the returned detections.

## Type of change

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality) - Segmentation tracking

## How has this change been tested, please provide a testcase or example of how you tested the change?

I have tested this change by running object tracking for both object detection and segmentation in this [colab notebook](https://colab.research.google.com/drive/1azgc_A-divM3Z5l0TyHW2SRHnw6EUlbO?usp=sharing)

segmentation_tracking

## Any specific deployment considerations

Tracking docs should be updated to reflect that ByteTrack can now do segmentation tracking.

## Docs

-   [ ] Docs updated? What were the changes:

### CODE REVIEW

**Comment by rolson24** [comment]
See this comment (https://github.com/roboflow/supervision/pull/1034#issuecomment-2016634735) about a question on possible change to the implementation.

**Comment by SkalskiP** [comment]
Hi @rolson24 👋🏻 ! Thanks a lot for your contribution. This is exactly what we needed. I'm super happy with this update.

**Review by SkalskiP — APPROVED** [review]

**Comment by SkalskiP** [comment]
Btw @rolson24, if you are feeling strong and have time, maybe try to work on [this](https://github.com/roboflow/supervision/issues/1044) issue.

**Comment by rolson24** [comment]
Hi @SkalskiP

I made a silly mistake in this PR with using enumerate to get the index of each track, because I forgot to test the new version. I have submitted another PR that fixes the issue. So sorry about this, I will try to remember to re-test every time before I submit a PR.

**Pull request merged**
