### PR TITLE
video generator with start and end position feature

### PR DESCRIPTION
**Pull request by hardikdava**
# Description

Related to #160 

## Type of change

-   [x] New feature (non-breaking change which adds functionality)
-   [x] This change requires a documentation update

## Docs

-   [ ] Docs updated? What were the changes:

### CODE REVIEW

**Comment by hardikdava** [comment]
@SkalskiP Please review it and merge it. I think docs needs to update for `start` and `end` argument.

**Comment by SkalskiP** [comment]
Awesome! 🔥  @hardikdava, did you test that on some example videos?

**Comment by hardikdava** [comment]
@SkalskiP I did some testing with various input parameters. It seems to work fine. I tried to improve the function with simple logic. Feel free to change or test it.

**Comment by hardikdava** [comment]
Hi @SkalskiP, I am wondering why these checks are failing. Do you know about it?

**Comment by hardikdava** [comment]
@SkalskiP I have a feeling that `yield` is slower compare to normal video reading.

**Comment by SkalskiP** [comment]
> I am wondering why these checks are failing. Do you know about it? 

We already have an issue to take a look at it https://github.com/roboflow/supervision/issues/138

> I have a feeling that `yield` is slower compare to normal video reading.

Yup. It is because you initially used `video.set` 2x. Once to set the initial position and once in the loop. I refactored it to use `video.set` only once.

**Comment by SkalskiP** [comment]
There was also another bug when `end was `None`. I managed to fix it. Could you take a look at the code once again and maybe test it on your vid once again? I think everything works now, but it never hurts to have multiple people looking at the code.

**Comment by SkalskiP** [comment]
Oh I don’t think it is a bug. We return different frame at the end because total frame count is not divisible by stride. If you would use stride=1 it would return the same last frame.

**Comment by hardikdava** [comment]
@SkalskiP I tested the code. It seems to work fine without any issue. Should we start discussing next task?

**Comment by SkalskiP** [comment]
Yeah! Let's do it tomorrow. Today I need to wrap a few things before `0.11.0` release :)

**Comment by hardikdava** [comment]
Okay. Let's do it tomorrow then. Can't wait to contribute more to the community.

**Review by SkalskiP — APPROVED** [review]

**Pull request merged**
