### PR TITLE
COCO categroy ids fix

### PR DESCRIPTION
**Pull request by hardikdava**
Fix for #150 issue

### CODE REVIEW

**Comment by SkalskiP** [comment]
Hi @hardikdava 👋🏻 If I understand your code correctly, you always subtract `1` from the class id. What if the class id already starts with `0`? Or if class_id values from COCO json are no consecutive numbers? For example `0`, `1`, and `3`?

**Comment by hardikdava** [comment]
Hi @SkalskiP , you are right. That can create an issue. But then what is the solution for this problem?

**Comment by SkalskiP** [comment]
Hi @hardikdava 👋🏻! Here is my proposed solution: https://github.com/roboflow/supervision/pull/176. My idea is to use the same `map_detections_class_id` we used in `sv.Dataset.merge`. As a result, we will map whatever class ids exist in the COCO annotation file to a format consistent with the rest of the `Dataset` logic.

**Comment by hardikdava** [comment]
@SkalskiP I will check it out and try to test it.

**Comment by SkalskiP** [comment]
@hardikdava awesome! 🔥 Thanks a lot!

**Comment by SkalskiP** [comment]
Closing this PR, as we developed alternative solution here: https://github.com/roboflow/supervision/pull/176

**Pull request closed without merging**
