### PR TITLE
LineZoneAnnotator: Align text to line counter in non-horizontal lines

### PR DESCRIPTION
**Pull request by jcruz-ferreyra**
# Description

In this pull request, I've enhanced `LineZoneAnnotator` class in `supervision/detection/line_counter.py` to align text with the `LineZone` object even when it is non-horizontal.

Additionally, I've introduced the option to omit drawing the text box behind the text, leveraging the optional condition on the `background_color` attribute in the `draw_text` method in `supervision/draw/utils.py.` Furthermore, users can now choose whether to draw the count centered in the `LineZone` object or aligned with its end, offering a solution to prevent overlaps in case of multiple LineZone objects in the same frame.

## Type of change

Please delete options that are not relevant.

-   [ ] New feature (non-breaking change which adds functionality)

## How has this change been tested, please provide a testcase or example of how you tested the change?

You can explore the results of the changes made in [this Colab notebook](https://colab.research.google.com/drive/19yobSRlqgX_s8k9_oRw0QgIipKDjs7hx?usp=sharing). I've tested `LineZone` objects with varying orientations and positions within the frame, as well as `LineZoneAnnotator` objects with different values for draw_text_box and draw_centered parameters.

NOTE: Personally, I don't fully like the circles drawn at the extremes of the `LineZone` objects. However, I chose not to modify them to maintain conciseness in the pull request. Given the introduction of the new `is_point_in_limits` method in the `LineZone` class, it might be more effective to draw a small line perpendicular to the main line (or even nothing at all) to emphasize this new functionality.

## Any specific deployment considerations

No specific deployment considerations. Just one parameter added as an attribute for LineZone Class with default value "both" mantaining previous implementation.

## Docs

No changes made to Docs

### CODE REVIEW

**Comment by jcruz-ferreyra** [comment]
Hi @SkalskiP! I was wondering if you've been able to check the PR

**Comment by LinasKo** [comment]
Hi @jcruz-ferreyra :wave: 

Thanks for keeping the branch up to date. I've seen your contribution before. I think it's very high quality and I believe we'll have time to look deeper in about a week.

Thanks for your patience - we've been swamped with work lately :)

**Comment by LinasKo** [comment]
Hi @jcruz-ferreyra 👋 

It's been a while, apologies for that. I'm planning to include this in the next supervision release.

Ahead of that, I moved some things around, cleaned up a few things.
Here's the Colab I used for testing: [Colab](https://colab.research.google.com/drive/1812rsq9aggpf60SJfaztuQyrGg9zQ-yi#scrollTo=6MkLJc--BCaq)

I'm happy to take over from this point onwards, for there's a few decisions to be made:

### 1. Is this too complicated?
I cannot deny the visuals are perfect. It looks 10x better than what we had. However, the code is inevitably more cumbersome, and we probably want to move it to utils somewhere, or remove a few of these features.

### 2. Is this too slow?
On a Colab, we can draw the new line zone 60 times a second, whereas previously we could do it 2000 times. At this point, realtime performance would be impacted, which I'd like to minimize.

### 3. Do we need the feature to draw off-center?
It adds much code, and it wasn't widely requested so far.

I'll park this for a few days and come back to finish it up later on.

**Comment by LinasKo** [comment]
Hey @jcruz-ferreyra 👋

I'm just putting a few finishing touches on the PR. I found ways to make the performance sane and the code more compact - we're keeping it, merging it, and retaining all the features you contributed 😉

Indeed, shame about OpenCV's lack of diagonality here. I've looked around, and everyone suggests a similar solution to what you added.

Thank you for volunteering to help out!
Feel free to send a PR our way if you spot a way to make the library better. Also, I haven't decided yet, but we may post a few issues for Hacktoberfest soon.

As for this PR, there's not much work left. I'll take over and get it done. Thank you for the contribution! 🚀

**Comment by LinasKo** [comment]
Leaving this for tomorrow. It feels like there's something slightly wrong with `_draw_basic_label` - the normal, unrotated labels are too close together.

Docs are checked.

Left to check: does commenting out the following code changes the distance between labels. Ideally it shouldn't.

```python
# Make sure text is displayed upright
if line_zone.vector.start.x > line_zone.vector.end.x:
    label_image = cv2.flip(label_image, flipCode=-1)
```

**Review by LinasKo — APPROVED** [review]

**Comment by jcruz-ferreyra** [comment]
Hey @LinasKo, those are great news! I'm glad the contribution was well received. Here's my LinkedIn profile:
https://www.linkedin.com/in/jcruz-ferreyra/

**Pull request merged**
