### PR TITLE
detectron2 mask convert to detection

### PR DESCRIPTION
**Pull request by kirilman**
# Description
Copying segmentation masks from detectron2 predictions to the detection class. The resulting masks can be used for displaying with sv.MaskAnnotator(). 

## Type of change

Please delete options that are not relevant.
-   [ ] New feature (non-breaking change which adds functionality)

## How has this change been tested, please provide a testcase or example of how you tested the change?
The code is executed:
detections = sv.Detections.from_detectron2(p_det)
bounding_box_annotator = sv.MaskAnnotator()
annotated_frame = bounding_box_annotator.annotate(
    scene=img.copy(),
    detections=detections,
)

### CODE REVIEW

**Comment by LinasKo** [comment]
Hi @kirilman 👋 

Does Detectron 2 produce masks every time? Are there cases when no mask would be produced?

**Comment by onuralpszr** [comment]
@LinasKo  Test collab with results 

https://colab.research.google.com/drive/1ich6f2UBOYXAV4AuKRt2mDi4trzXfs0w?usp=sharing

With and without mask result and original vis result, If all good I am merging

**Review by LinasKo — APPROVED** [review]
Indentation looked peculiar, but it seems the pre-commit formats it this way.

**Comment by LinasKo** [comment]
Hi @kirilman 👋 

This is a great contribution, and together with @onuralpszr's change, we'd really like to use it in our repository!

However, before we do, you need to sign the [Contributor License Agreement](https://cla-assistant.io/roboflow/supervision?pullRequest=1300). Can you please follow the link and complete it?

Thank you!

**Comment by kirilman** [comment]
> Hi @kirilman 👋
> 
> Does Detectron 2 produce masks every time? Are there cases when no mask would be produced?
Yes, you're right. We need to think about the case of no mask

**Comment by onuralpszr** [comment]
> > @LinasKo  👋
> > Does Detectron 2 produce masks every time? Are there cases when no mask would be produced?
> 
> Yes, you're right. We need to think about the case of no mask

I already cover that part in your PR branch could you please accept CLA so we can merge :)

**Comment by LinasKo** [comment]
Indeed, the CLA allows us to include your code, @kirilman

**Comment by onuralpszr** [comment]
@kirilman thank you for validation 

@LinasKo merge complete :)

**Comment by LinasKo** [comment]
Thank you @kirilman , @onuralpszr !

**Comment by onuralpszr** [comment]
> Thank you @kirilman, @onuralpszr!

You're welcome, Pleasure ❤️

**Pull request merged**
