### PR TITLE
Update CONTRIBUTING.md file

### PR DESCRIPTION
**Pull request by capjamesg**
This PR updates the `CONTRIBUTING.md` file per Issue #283.

### CODE REVIEW

**Comment by SkalskiP** [comment]
@capjamesg great progress here! That looks exactly how I imagined it. 🔥 

Please make sure to take a look at https://github.com/roboflow/supervision/issues/283 and add @onuralpszr and @hardikdava suggestions. 🙏🏻

**Comment by capjamesg** [comment]
I have made more changes!

@hardikdava Can you elaborate on:

> Add section for license agreement and if license of function/algorithm is not supporting MIT license then discuss issues with maintainers.

**Comment by SkalskiP** [comment]
@hardikdava and @capjamesg, are we ready to merge here?

**Comment by hardikdava** [comment]
> I have made more changes!
> 
> @hardikdava Can you elaborate on:
> 
> > Add section for license agreement and if license of function/algorithm is not supporting MIT license then discuss issues with maintainers.

For example, a new/existing contributor wants to add some new feature like ultralytics model directly to supervision. But ultralytics is not released under MIT license but supervision is under MIT license. There will be an issue with the license which is not good. In such scenario, it would be better to talk to maintainer.

**Comment by onuralpszr** [comment]
Example License listing : https://github.com/roboflow/inference#-license
+1 @hardikdava  says as well.

**Comment by capjamesg** [comment]
Almost @SkalskiP! @hardikdava should we say that we will only accept contributions that can be licensed under MIT?

**Comment by onuralpszr** [comment]
@capjamesg reference : https://github.com/ultralytics/ultralytics/blob/main/CONTRIBUTING.md#license

**Comment by capjamesg** [comment]
@onuralpszr Added a sentence on license information ✅

**Comment by SkalskiP** [comment]
I think we can merge :) If we think about anything else we want to add, we can always open PR for that specific thing. I think it is way better `CONTRIBUTING.md`! 🔥

**Review by SkalskiP — APPROVED** [review]

**Pull request merged**
