### PR TITLE
Update README.md example for looping through dataset

### PR DESCRIPTION
**Pull request by lomnes-atlast-food**
Example in README documentation out of date for v.0.8.0.  __iter__() yields a length 3 tuple.  Example shows a length 2 tuple. 

Change proposed: add image_name to example to align with current version of DetectorDataset objects.

Reference: From API docs

```
__iter__() ¶
Iterate over the images and annotations in the dataset.

Yields:

Type	Description
Iterator[Tuple[str, np.ndarray, Detections]]	
Iterator[Tuple[str, np.ndarray, Detections]]: An iterator that yields tuples containing the image name, the image data, and its corresponding annotation.
```

# Description

Please include a summary of the change and which issue is fixed or implemented. Please also include relevant motivation and context (e.g. links, docs, tickets etc.).

List any dependencies that are required for this change.

## Type of change
[X] Documentation update

## How has this change been tested, please provide a testcase or example of how you tested the change?

Example in README yields error 
```python
for image, label in dataset:
    print(label.xyxy)
    
ValueError: too many values to unpack (expected 2)
```

Changed example does not yield error:
```python
for image_name, image, label in dataset:
    print(label.xyxy)
```

## Any specific deployment considerations

Did not check all other documents for instances of this change not being updated.

## Docs

-   [X] Docs updated? What were the changes: Change to example in README.md file.

### CODE REVIEW

**Review by SkalskiP — APPROVED** [review]

**Comment by SkalskiP** [comment]
Hi @lomnes-atlast-food 👋🏻! Absolutely. This was my intention. Thanks a lot for spotting the error. I see you work with our `Dataset` API. I hope you don't mind me asking, did you find it intuitive?

**Comment by lomnes-atlast-food** [comment]
@SkalskiP Happy to help!  I came for the Detections API but will stay because of the Dataset API.  :-)

Very handy to use and helpful for simplifying lots of steps and removing chunks of code that I had already written (badly) for my own applications.  Thank you soooo much!  The `.as_*()`methods and everything they rely on are such a helpful thing to have (masks to polygons to normalized polygons etc. are now easily abstracted away). Being able to bundle all the data into a single `Dataset` object is very simplifying.

I've been working with yolov8 which seems to have a different data.yaml format, at least when training with ultralytics.  So the only thing I've had to work around with data sets is that.  The other thing that might simplify things is providing an option to specify train, test, split in the `.as_*()` methods. 

All in all,  it's a delightful package that you've built!  It goes a long way to making vision applications accessible and fluid for people.

**Comment by SkalskiP** [comment]
Hello once again, @lomnes-atlast-food 👋🏻! Apologies for not responding. I had a presentation at a conference, and I needed to focus on that. Thanks a lot for those kind words. It is fantastic to read comments like that and validate assumptions I made months ago when `supervision` was just an idea. I hope you will stay with us. I think the community really needs people like you. 💜

**Comment by SkalskiP** [comment]
@lomnes-atlast-food as for `data.yaml`

> I've been working with yolov8 which seems to have a different data.yaml format, at least when training with ultralytics.

The problem is that `data.yaml` combines information - specifically paths - from 3 subsets. I am aware of that problem. In general YOLO API might change in the future. We use that API internally and we see some problems that we need to solve. We will try to communicate that as clearly as possible.

**Pull request merged**
