### PR TITLE
Added PercentageBarAnnotator Class

### PR DESCRIPTION
**Pull request by xaristeidou**
# Description

Added PercentageBoxAnnotator annotation, which shows the confidence level of the predictions

List any dependencies that are required for this change.

## Type of change

Please delete options that are not relevant.

-   [x] New feature (non-breaking change which adds functionality)
-   [x] This change requires a documentation update

## How has this change been tested, please provide a testcase or example of how you tested the change?

Predicted with YOLOv8 and plotted annotation with PercentageBarAnnotator annotation class and Detections class (for detections results). 

## Any specific deployment considerations

Additional feature

## Docs

-   [ ] Docs updated? What were the changes: Just added Class and function descriptions

## Further improvement

-   [x]  Have to add functionality for position selection

Screenshot from 2023-10-13 14-56-55

### CODE REVIEW

**Comment by SkalskiP** [comment]
Hi @xaristeidou 👋🏻 Sorry it took me so long to respond. I was on the Christmas break. This is awesome PR. I'm sorry to see it being closed. 

Did you close it by accident? Because, it looks like it got closed because you deleted the fork repository.

**Comment by SkalskiP** [comment]
I like it so much that I'm taking the liberty of reopening this PR.

**Comment by xaristeidou** [comment]
@SkalskiP The code was a bit of incomplete because there was not dynamic positioning using Position class, and also had some problems when choosing high values to make thebar bigger. I have a new issue #695 which demonstrates a new implementation with Position settings and width, height. Take a look at that, and if it is good i can submit a PR!! 

Thanks for answering!

**Comment by SkalskiP** [comment]
Super! I was a little scared that you were discouraged by my lack of response. If you have time, I am motivated and have time to add this feature by the end of the year.

**Pull request closed without merging**
