### PR TITLE
Add Discord button to README

### PR DESCRIPTION
**Pull request by capjamesg**
This PR adds a Discord invitation button to the README.

### CODE REVIEW

**Comment by onuralpszr** [comment]
@capjamesg please take look here  https://shields.io/badges/discord 

You can customize by clicking "show optional parameters" you also need to enable widget which you can see in the video how to enable as well. We can also achieve the style @SkalskiP want as well.

**Comment by SkalskiP** [comment]
I tried to plug it into our discord but couldn't figure it out. :/ @capjamesg, could you try it out?

**Comment by onuralpszr** [comment]
> I tried to plug it into our discord but couldn't figure it out. :/ @capjamesg, could you try it out?

you can try with different public server to "see results" for us we need to enable server widget

**Comment by capjamesg** [comment]
I have updated the button to use the shields.io button.

**Review by SkalskiP — APPROVED** [review]

**Comment by SkalskiP** [comment]
Looks good @capjamesg! I'm merging. 🔥

**Pull request merged**
