### PR TITLE
Add `sv.RoundBoxAnnotator` which annotates bounding box with round edges

### LINKED ISSUE #693: Add annotator RoundBoundingBoxAnnotator which has rectangle with round edges
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Description

I have created a new annotator class named `RoundBoundingBoxAnnotator` which draws bounding box with rounded edges. 

`RoundBoundingBoxAnnotator` has the same attributes with `BoundingBoxAnnotator` including one extra attribute `roundness` which accepts float values `0 < roundness <= 1.0`. Roundness attribute controls the percentage of edge roundness based each time on the lower length of width or height, for each object independently. 

You can see some examples with `roundness = 0.5 `and `roundess = 1.0` in the following screenshots.

` round_box_annotator = sv.RoundBoundingBoxAnnotator(thickness=2, roundess=0.5)`
roundness_05

` round_box_annotator = sv.RoundBoundingBoxAnnotator(thickness=2, roundess=1.0)`
roundness_1

I have created two different cases of `RoundBoundingBoxAnnotator`. The first one has the same `color` and `thickness` for edges and lines of the box. The second one can accept different values for `color` and `thickness`. You can view a demo video for each case below.

I think this annotator look cool and could be included in Supervision API. I can't decide which one looks better or if extra feature for different color and thickness of edges and lines is too much or not. Let me know your thoughts.

https://github.com/roboflow/supervision/assets/65918758/c5c21ec5-79b1-483b-9b66-36b098b11ee2

https://github.com/roboflow/supervision/assets/65918758/76150e2f-e743-41f7-bf3b-810bfbe4e0d9

### Use case

_No response_

### Additional

_No response_

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by xaristeidou**
# Description

This annotator will draw a bounding box which has round edges based on `roundness` attribute which accepts float values < `roundness` <= 1.0. 

By default, roundness attribute percentage value is calculated based on the smaller size dimension (width or height). For example if height < width, and roundness is 1.0, the height dimension will be rounded completely.

This PR implements issue #693. (Fix #693)

Execution time of annotation process (tested on Ryzen 7 5800H):
- Exec time for 35 objects: 0.0018765926361083984
- Mean exec time for each object: 5.361693246023995e-05

**No new dependencies required for this change.**

-   [x] New feature (non-breaking change which adds functionality)
-   [x] This change requires a documentation update

I tested annotation results on walking people demo video. I used YOLOv8 to get the detection results. Screenshot of demo, using `roundness = 0.5`,  is presented below:
roundness_05

## Any specific deployment considerations

- Add new annotator class in Documentation.
- Add image example link reference in class Description in annotators/core.py

## Docs

Docs not updated. Need to be updated with new annotator.

### CODE REVIEW

**Comment by onuralpszr** [comment]
@xaristeidou hello, first of it looks amazing. 🚀  I am taking the review.

**Comment by onuralpszr** [comment]
Simple Test Collab Link and python code

Google Collab link [here](https://colab.research.google.com/drive/1BPHkhHJ95Z5oRqzTHy82J5BxXxAD4SDu?usp=sharing)

```python
#!pip install git+https://github.com/xaristeidou/supervision.git@develop
#!pip install requests tqdm ultralytics

import supervision as sv
from supervision.assets import download_assets, VideoAssets

download_assets(VideoAssets.PEOPLE_WALKING)

from ultralytics import YOLO
model = YOLO('yolov8x-seg.pt')

frames_generator = sv.get_video_frames_generator(source_path='people-walking.mp4')
frames_iterator = iter(frames_generator)
frame = next(frames_iterator)
sv.plot_image(image=frame, size=(12, 12))

result = model.track(frame)[0]
detections = sv.Detections.from_ultralytics(result)

round_bounding_box_annotator = sv.RoundBoundingBoxAnnotator()
annotated_frame = round_bounding_box_annotator.annotate(scene=frame.copy(), detections=detections)
sv.plot_image(image=annotated_frame, size=(12, 12))


```

**Comment by onuralpszr** [comment]
cc @SkalskiP I did checks and write docs parts and also made collab part for testing so can you also check and upload the image to server so it can show up as well.

**Review by onuralpszr — APPROVED** [review]

**Comment by SkalskiP** [comment]
@onuralpszr, can we make the name a bit shorter? I was thinking about `RoundBoxAnnotator`.

**Comment by onuralpszr** [comment]
@SkalskiP  rename done. And test code and collab also changed as well.

**Comment by onuralpszr** [comment]
Thanks to @capjamesg's help he uploaded the pictures for docs so I am merging. Thank you all !

**Pull request merged**
