### PR TITLE
feat: 🚀 Keypoint support for detectron2 

### PR DESCRIPTION
**Pull request by onuralpszr**
# Description

This PR adds support for keypoints support for detectron2 model

## Type of change

Please delete options that are not relevant.

-   [X] New feature (non-breaking change which adds functionality)
-   [X] This change requires a documentation update

## How has this change been tested, please provide a testcase or example of how you tested the change?

https://colab.research.google.com/drive/19nA7-MZQbPPMhtBbpMEpmRcpemwqSatJ?usp=sharing

## Docs

-   [X] Docs updated? What were the changes:

### CODE REVIEW

**Comment by LinasKo** [comment]
I ran the colab with `im = np.zeros((640, 640, 3), dtype=np.uint8)`.

The `from_detectron2` function threw this error:
`ValueError: xy must be a 2D np.ndarray with shape ((0, 0),), but got shape (0, 17, 2)`.

Is that something we can handle?

**Comment by onuralpszr** [comment]
> I ran the colab with `im = np.zeros((640, 640, 3), dtype=np.uint8)`.
> 
> The `from_detectron2` function threw this error: `ValueError: xy must be a 2D np.ndarray with shape ((0, 0),), but got shape (0, 17, 2)`.
> 
> Could you look into that?

Sure let me check it. I didn't see this comment ( missed or didn't get notify from email or github at mobile sorry)

**Comment by onuralpszr** [comment]
@LinasKo empty case fixed.  sorry for late response legit did not see it.

**Review by LinasKo — APPROVED** [review]
There are small imperfections with the Colab, but overall it looks good!

Thank you @onuralpszr!

**Pull request merged**
