### PR TITLE
feat(DEFAULT_COLOR_PALETTE): ✨ Replace Default Color Palette with Default Matplotlib Colors

### PR DESCRIPTION
**Pull request by hi-sushanta**
DEFAULT_COLOR_PALETTE variable value manually defines each of these colors so I changed this to the matplotlib color module for more color options available.

**Previous Code**
Screenshot from 2023-08-25 05-35-18

**Changed Code Look Like**
Screenshot from 2023-08-25 05-36-44

### CODE REVIEW

**Comment by SkalskiP** [comment]
Hi, @hi-sushanta 👋🏻! Thanks for your interest in supervision.

I have a few questions:
- Is it the same color palette we use right now as default?
- Is the only reason for this change to make the code shorter?

**Comment by onuralpszr** [comment]
> Hi, @hi-sushanta 👋🏻! Thanks for your interest in supervision.
> 
> I have a few questions:
> 
> * Is it the same color palette we use right now as default?
> * Is the only reason for this change to make the code shorter?

I check chose colors and it is not the same


['#F0F8FF', '#FAEBD7', '#00FFFF', '#7FFFD4', '#F0FFFF', '#F5F5DC', '#FFE4C4', '#000000', '#FFEBCD', '#0000FF', '#8A2BE2', '#A52A2A', '#DEB887', '#5F9EA0', '#7FFF00', '#D2691E', '#FF7F50', '#6495ED', '#FFF8DC', '#DC143C', '#00FFFF', '#00008B', '#008B8B', '#B8860B', '#A9A9A9', '#006400', '#A9A9A9', '#BDB76B', '#8B008B', '#556B2F', '#FF8C00', '#9932CC', '#8B0000', '#E9967A', '#8FBC8F', '#483D8B', '#2F4F4F', '#2F4F4F', '#00CED1', '#9400D3', '#FF1493', '#00BFFF', '#696969', '#696969', '#1E90FF', '#B22222', '#FFFAF0', '#228B22', '#FF00FF', '#DCDCDC', '#F8F8FF', '#FFD700', '#DAA520', '#808080', '#008000', '#ADFF2F', '#808080', '#F0FFF0', '#FF69B4', '#CD5C5C', '#4B0082', '#FFFFF0', '#F0E68C', '#E6E6FA', '#FFF0F5', '#7CFC00', '#FFFACD', '#ADD8E6', '#F08080', '#E0FFFF', '#FAFAD2', '#D3D3D3', '#90EE90', '#D3D3D3', '#FFB6C1', '#FFA07A', '#20B2AA', '#87CEFA', '#778899', '#778899', '#B0C4DE', '#FFFFE0', '#00FF00', '#32CD32', '#FAF0E6', '#FF00FF', '#800000', '#66CDAA', '#0000CD', '#BA55D3', '#9370DB', '#3CB371', '#7B68EE', '#00FA9A', '#48D1CC', '#C71585', '#191970', '#F5FFFA', '#FFE4E1', '#FFE4B5', '#FFDEAD', '#000080', '#FDF5E6', '#808000', '#6B8E23', '#FFA500', '#FF4500', '#DA70D6', '#EEE8AA', '#98FB98', '#AFEEEE', '#DB7093', '#FFEFD5', '#FFDAB9', '#CD853F', '#FFC0CB', '#DDA0DD', '#B0E0E6', '#800080', '#663399', '#FF0000', '#BC8F8F', '#4169E1', '#8B4513', '#FA8072', '#F4A460', '#2E8B57', '#FFF5EE', '#A0522D', '#C0C0C0', '#87CEEB', '#6A5ACD', '#708090', '#708090', '#FFFAFA', '#00FF7F', '#4682B4', '#D2B48C', '#008080', '#D8BFD8', '#FF6347', '#40E0D0', '#EE82EE', '#F5DEB3', '#FFFFFF', '#F5F5F5', '#FFFF00', '#9ACD32']



And what I assume is make more color and shorter code and more colors but do we need that much of color ?

**Comment by hi-sushanta** [comment]
**Question(1):** Is it the same color palette we use right now as default?
**Answer:** The color palette in the first code snippet is not the same as the default color palette in Matplotlib. The default color palette in Matplotlib has 148 colors, while the first code snippet defines a custom color palette with 15 colors.

**Question(2):** Is the only reason for this change to make the code shorter?
**Answer:** The reason for changing the code is not only to make it shorter. It is also to use a more consistent color scheme and to use colors that are more meaningful to the data being visualized.

**Comment by hi-sushanta** [comment]
If you see my answer?

**Comment by SkalskiP** [comment]
Hi, @hi-sushanta 👋🏻! Yes, we do. I just was AFK for the past two days. Let me do a few tests, and I'll get back to you.

**Comment by hi-sushanta** [comment]
Ok, thank you for responding.

**Comment by hi-sushanta** [comment]
Hello, How much time take to get back to my pull request?

**Comment by onuralpszr** [comment]
@hi-sushanta I check the matplotlib color palette and I see that results are not completely okay. For example I see some of the detections has black box with black text or I see more white box and not red (usually primary colors or more visible)

Let me show you some of the problematic results

image

Before image results

image

New color palette 

image

**Comment by hi-sushanta** [comment]
I added new functionality for only using high contrast colour.

**Comment by onuralpszr** [comment]
@hi-sushanta  you also need to fix license/cla problem is second committer you or someone else ? Also you did test it ?  any result can you show ?

**Comment by hi-sushanta** [comment]
Yes, it's me.

**Comment by hi-sushanta** [comment]
I already signed CLA but it always shows as license cla pending.

**Comment by onuralpszr** [comment]
> I already signed CLA but it always shows as license cla pending.

you can  try  replace that commit author with yours via rebase

**Comment by onuralpszr** [comment]
@hi-sushanta  what ? :)

**Comment by hi-sushanta** [comment]
I am really sorry for that. and I try to fix that.

**Comment by hi-sushanta** [comment]
I closed this pull request and again back to the new pull request.

**Comment by hi-sushanta** [comment]
I solve this license problem.

**Comment by SkalskiP** [comment]
Hi, @hi-sushanta and @onuralpszr 👋🏻 I have been on vacation for the past few weeks. I am trying to get back to the rhythm of work.

Unfortunately, I have decided to close this PR.

- Our conversation under this PR proves that creating a set of colors we could use in our annotators is challenging.
- It is especially difficult to generate such a color palette procedurally. 
- By the way, I am not a big fan of the palette we have now. It is simply good enough. And I am open to changing it in the future.
- From experience, we do not need 100+ colors. In most projects, less than 10 categories are used.
- We certainly need to define custom pallets as easily as possible. 

@hi-sushanta I hope you understand my decision. Thank you also very much for the time you spent working on this PR, even if we didn't merge it.

**Pull request closed without merging**
