### PR TITLE
Feature Addition: Time Tracking in ByteTracker.

### PR DESCRIPTION
**Pull request by AdonaiVera**
# Description

This PR introduces a new feature to the ByteTracker, adding the capability to track and display the time associated with each object being tracked. This enhancement is particularly aimed at applications in retail analytics, where understanding the duration of customer interactions or movements is crucial. The addition of this feature allows for more in-depth analysis and insights into human behaviors within retail environments.

Screenshot 2024-01-10 at 3 04 46 AM

## Type of change

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [X] New feature (non-breaking change which adds functionality)
-   [ ] This change requires a documentation update

## How has this change been tested, please provide a testcase or example of how you tested the change?

A demo notebook in Google Colab was created to showcase the functionality in a controlled environment: 
[Google Colab Demo](https://colab.research.google.com/drive/17fTvJwgQa0-JWM_tn4EOARMt1gT6iNHK?usp=sharing)

## Any specific deployment considerations

No additional considerations are required for deployment. 

## Docs

-   [X] Docs updated? What were the changes:

    - Added documentation for the new time tracking feature in ByteTracker.
    - Included examples and use cases, specifically in retail analytics.
    - Updated API references to include new parameters and usage instructions.

---

I believe this feature can greatly benefit the community, especially those working with computer vision in retail and similar domains. Looking forward to your feedback and further collaboration! 🚀 🧗

### CODE REVIEW

**Comment by AdonaiVera** [comment]
This is a video of the result. 🚀 


https://github.com/roboflow/supervision/assets/45982251/c135862c-8fb1-4ac1-a838-2c964d65bd91

**Comment by SkalskiP** [comment]
Hi, @AdonaiVera 👋🏻 Thanks for your interest in `supervision`. Sorry, it took me so much time to respond. I know you tried to reach out to me not only here but also on social media. It's just too many things I need to do at once. 

As for your PR. I think time calculation should not be part of tracker logic. I'm working on timer logic right now, and I plan to add it as a stand-alone tool - independent of tracking. That's why I'm afraid I need to close this PR. 

Saying that, we have a lot of tasks planned that we would need help with. Would you be interested?

**Comment by AdonaiVera** [comment]
Hi @SkalskiP 
Sounds great! Let me know how I can help with any task you suggest.

I'm interested in making contributions to the computer vision community. 🥷🚀

**Comment by SkalskiP** [comment]
@AdonaiVera Great! By Monday, we should have an updated list of tasks ready. Many of them will relate to ByteTrack, so the time you spent mastering this part of the code will not be wasted.

**Comment by AdonaiVera** [comment]
Amazing, thank you @SkalskiP 🚀

**Pull request closed without merging**
