### PR TITLE
Add ZoomInfo integration

### PR DESCRIPTION
**Pull request by capjamesg**
# Description

This PR adds ZoomInfo to the supervision documentation.

## Type of change

Adding a script to the documentation.

## How has this change been tested, please provide a testcase or example of how you tested the change?

This change can be tested by checking for the presence of the ZoomInfo script on the site when served locally with `mkdocs serve`.

## Any specific deployment considerations

N/A

## Docs

N/A

### CODE REVIEW

**Comment by capjamesg** [comment]
Here is the script showing on the supervision docs homepage:

Screenshot 2023-12-21 at 15 02 52

**Comment by onuralpszr** [comment]
@capjamesg btw couldn't be better to use banner on readme page as well ?

**Review by SkalskiP — APPROVED** [review]

**Comment by SkalskiP** [comment]
@capjamesg I merged the PR. Please test if the expected changes have been added to the docs page. 

Curious if we could measure people visiting our GitHub `README.md` somehow.

**Comment by capjamesg** [comment]
It works as expected in production -- thanks!

**Comment by SkalskiP** [comment]
Awesome! That's what I wanted to hear ;)

**Pull request merged**
