### PR TITLE
fix: 🐞 poetry numpy version has been set based on python version

### PR DESCRIPTION
**Pull request by onuralpszr**
I made extra bit of research and I notice it was actually happening because of lack of numpy version poetry locked in toml file so I set min and max for py10 and version for py10 above (I set to first py11 supported version as min since it is the first version has wheels for py11) 

Fix: #1378 

I tested with tox and with poetry(py8,py9,py10,py11,py12)

### CODE REVIEW

**Comment by onuralpszr** [comment]
Tox result

image

**Comment by onuralpszr** [comment]
@SkalskiP technically this should be done automatically but somehow poetry failed to find proper numpy version I forced and made more obvious selection so it can find proper version (by force)

**Comment by SkalskiP** [comment]
Hi @onuralpszr 👋🏻, have you managed to test this PR?

**Comment by onuralpszr** [comment]
> Hi @onuralpszr 👋🏻, have you managed to test this PR?

Yes ? I wrote all

**Comment by onuralpszr** [comment]
> I tested with tox and with poetry(py9,py10,py11,py12)
 
 @SkalskiP  I did both :)

**Review by SkalskiP — APPROVED** [review]

**Comment by SkalskiP** [comment]
I'm sorry @onuralpszr 🙏🏻 merging!

**Comment by onuralpszr** [comment]
> I'm sorry @onuralpszr 🙏🏻 merging! 

Thank you, no need to be sorry, I should of check extra carefully too. Sorry the that.

**Pull request merged**
