### PR TITLE
Add ultralytics SAM support when using `bboxes` and `points` arguments in `SAM().predict()`

### PR DESCRIPTION
**Pull request by xaristeidou**
# Description

Fixes issue noted in #1453 .

Added brief check and fill of necessary fields in sv.Detections()

List any dependencies that are required for this change.

**No new dependencies**

Please delete options that are not relevant.

-   [x] Bug fix (non-breaking change which fixes an issue)

## How has this change been tested, please provide a testcase or example of how you tested the change?

Colab attached for testing

## Docs

-   [ ] Docs updated? **Not needed**

Colab notebook for testing: https://colab.research.google.com/drive/10aRaBAfb__xrMeBNn9amYwrKgcnbExBn?usp=sharing

### CODE REVIEW

**Comment by xaristeidou** [comment]
`class_id=np.arange(len(ultralytics_results)),` : This is due to the fact that if there are more than one masks, their class_id is labeled with increasing +1 step start from 0 (e.g. 0,1,2, etc).

**Comment by xaristeidou** [comment]
Why does pre-commit check fails, mask_to_xyxy is imported properly and runs as expected locally. Locally in my system pre-commit pass all checks.

**Comment by onuralpszr** [comment]
@xaristeidou  I also added maskl to xyxy  and pre-commit locally fine at my end.  Probably some server issue. I tested with normal cases as well. LGTM to me !

**Comment by onuralpszr** [comment]
> Why does pre-commit check fails, mask_to_xyxy is imported properly and runs as expected locally. Locally in my system pre-commit pass all checks.

I think server issue I have no idea

**Comment by onuralpszr** [comment]
@xaristeidou  I am going to update your branch to latest dev and test that out before merge maybe pre-commit will act fine I will backup and revert in case something happen.

**Comment by onuralpszr** [comment]
@xaristeidou  I understand why act weird because in our CURRENT develop we removed that import so compare to latest makes fail so I had to update repo and re-add again to fix it.  Now it is all good.

**Comment by xaristeidou** [comment]
@onuralpszr Nice! Makes sense now.

**Comment by onuralpszr** [comment]
I am merging in. Thank you so much @xaristeidou !

**Review by onuralpszr — APPROVED** [review]

**Pull request merged**
