### PR TITLE
feat: adding type hinter markers in package

### PR DESCRIPTION
**Pull request by DemyCode**
# Description

https://safjan.com/the-importance-of-adding-py-typed-file-to-your-typed-package/

## Type of change

Please delete options that are not relevant.

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [X] New feature (non-breaking change which adds functionality)
-   [ ] This change requires a documentation update

## How has this change been tested, please provide a testcase or example of how you tested the change?

N/A

## Any specific deployment considerations

N/A

## Docs

-   [ ] Docs updated? What were the changes:

### CODE REVIEW

**Comment by onuralpszr** [comment]
@DemyCode  hello and could you accept CLA please 👋

**Comment by DemyCode** [comment]
Hello @onuralpszr I accepted the CLA what should I do next ? Any requirements for this PR ? It is a very simple one.

**Comment by LinasKo** [comment]
Hi @DemyCode :wave:

Is there a way we could see the types not appearing in any editor, and then appearing after the file is added?

My VSCode was smart enough up until this point, so I didn't notice we had this problem.

If we can't practically prove it - I'm on the fence whether we should add it.

**Comment by onuralpszr** [comment]
@LinasKo, we should add py.typed to support mypy and follow PEP 561. Additionally, we need to implement a new namespace in line with PEP 420. Our IDEs/editors should mostly handle this well, but it will improve typing and stub cases for better clarity.

#### References:
- [PEP 561 – Distributing and Packaging Type Information](https://www.python.org/dev/peps/pep-0561/)
- [mypy Documentation on PEP 561](https://mypy.readthedocs.io/en/stable/installed_packages.html#installed-packages)
- [Packaging Typed Libraries](https://typing.readthedocs.io/en/latest/spec/distributing.html#packaging-typed-libraries)
- [Implicit Namespace Packages - PEP 420](https://peps.python.org/pep-0420/)

**Comment by LinasKo** [comment]
I'll have a look! Thanks @onuralpszr !

**Comment by LinasKo** [comment]
I've learnt something today. Thank you @DemyCode and @onuralpszr!
Definitely merging this one, provided that CI passes.

**Review by LinasKo — APPROVED** [review]

**Pull request merged**
