### PR TITLE
Updated inference_slicer.py

### LINKED ISSUE #781: Batch size inference slicer
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Description

As far as I understood the code. The Inference slicer runs over N slices performing inference N times with batch=1. Are you planning to add a batch size parameter? Ideally a single forward pass with batch N, the number of slices. That’d speed up inference! Ty:)

### Use case

_No response_

### Additional

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by Bhavay-2001**
# Description

Fixes #781

## Type of change

Please delete options that are not relevant.

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [x] This change requires a documentation update

## How has this change been tested, please provide a testcase or example of how you tested the change?

Testing needs to be done. Would like the maintainers to suggest changes

## Any specific deployment considerations

For example, documentation changes, usability, usage/costs, secrets, etc.

## Docs

-   [ ] Docs updated? What were the changes:

### CODE REVIEW

**Comment by Bhavay-2001** [comment]
Hi @SkalskiP, can you please review this PR and let me know about the possible changes.

**Comment by SkalskiP** [comment]
Can you accept the CLA?

**Comment by Bhavay-2001** [comment]
Yes, Done!

**Comment by Bhavay-2001** [comment]
I have signed the CLA but I am using my brother's laptop and he doesn't have a GitHub account, so how can I remove his name from this?

**Comment by SkalskiP** [comment]
You need to git config https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup with your GitHub nick and email BEFORE you commit code to branch.

**Comment by Bhavay-2001** [comment]
Should I just delete this branch and add the changes from my own laptop with my settings?

**Pull request closed without merging**
