### PR TITLE
Add timm data loader for `sv.Classifications`

### PR DESCRIPTION
**Pull request by capjamesg**
# Description

This PR adds a data loader for classifications from the `timm` Python package.

## Type of change

-   [X] New feature (non-breaking change which adds functionality)

## How has this change been tested, please provide a testcase or example of how you tested the change?

You can test the API using the following code:

```python
import timm
import torch
from PIL import Image
from timm.data import resolve_data_config
from timm.data.transforms_factory import create_transform
import supervision as sv

# Load from Hub 🔥
model = timm.create_model(
    'hf-hub:nateraw/resnet50-oxford-iiit-pet',
    pretrained=True
)

# Set model to eval mode for inference
model.eval()

# Create Transform
transform = create_transform(**resolve_data_config(model.pretrained_cfg, model=model))

# Get the labels from the model config
labels = model.pretrained_cfg['label_names']
top_k = min(len(labels), 5)

# Use your own image file here...
image = Image.open('./annotated_image.jpg').convert('RGB')

# Process PIL image with transforms and add a batch dimension
x = transform(image).unsqueeze(0)

# Pass inputs to model forward function to get outputs
out = model(x)

results = sv.Classifications.from_timm(out)

print(results)
```

## Any specific deployment considerations

N/A

## Docs

This PR does not yet contain a docs update, but I will add documentation for the method as part of this PR.

### CODE REVIEW

**Comment by SkalskiP** [comment]
@capjamesg, is that PR ready for review? I see it is still marked as `Draft`. 

btw, just want to remind you about: `Please share a Google Colab with minimal code to test new feature or reproduce PR whenever it is possible. Please ensure that Google Colab can be accessed without any issue.`

**Comment by SkalskiP** [comment]
@capjamesg pre-commit is failing can you fix this?

**Comment by capjamesg** [comment]
@SkalskiP Here is a Colab for this PR: https://colab.research.google.com/drive/1eHmk_5GgdqI2wGj08UZbQ0peNTKVG4b2?usp=sharing

**Review by SkalskiP — APPROVED** [review]

**Comment by SkalskiP** [comment]
Awesome! Thanks a lot, @capjamesg! 🙏🏻 Merging!

**Pull request merged**
