### PR TITLE
Added rtdetr method

### PR DESCRIPTION
**Pull request by Bhavay-2001**
# Description

Fixes issue #1418 

## Type of change

Please delete options that are not relevant.

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] This change requires a documentation update

## How has this change been tested, please provide a testcase or example of how you tested the change?

Colab [notebook](https://colab.research.google.com/drive/1jIS0cZAyXnJe14jtUEwKehB75JY8XLWl?usp=sharing)

## Any specific deployment considerations

For example, documentation changes, usability, usage/costs, secrets, etc.

## Docs

-   [ ] Docs updated? What were the changes:

Reviewer - @LinasKo @SkalskiP

### CODE REVIEW

**Comment by LinasKo** [comment]
Hi @Bhavay-2001,

I see this is coming from `transformers`. If that's the case, the model should already be supported via the `from_transformers` connector.

Note that we may not support `post_process_object_detection` yet (only the legacy `post_process` method), but that is already being worked on, on PR #1386.

Are `transformers` the main way this model is called?

**Comment by Bhavay-2001** [comment]
> Hi @Bhavay-2001,
> 
> I see this is coming from `transformers`. If that's the case, the model should already be supported via the `from_transformers` connector.
> 
> Note that we may not support `post_process_object_detection` yet (only the legacy `post_process` method), but that is already being worked on, on PR #1386.
> 
> Are `transformers` the primary framework for calling this model?

Yes, I am loading this model from the `transformer` library of hugging face.

**Comment by Bhavay-2001** [comment]
Hi @LinasKo, should I close this one for now?

**Comment by LinasKo** [comment]
Hey @Bhavay-2001,

Yes, let's close it for now. Thank you for keeping your eyes open for potential improvements. Apologies for not stopping you a bit earlier - I wasn't sure if RT-DETR is standalone or primarily a transformers model. Could have saved you a bit of time 😅

**Comment by Bhavay-2001** [comment]
No worries. There is this [issue](https://github.com/roboflow/supervision/issues/1295) which requires work on obb. I have worked on obb before so should I try to work on this one?

**Comment by SkalskiP** [comment]
Hi, @Bhavay-2001 👋🏻  `from_transformers` works with the RT-DETR `transformers` model. Take a look [here](https://colab.research.google.com/github/roboflow-ai/notebooks/blob/main/notebooks/train-rt-detr-on-custom-dataset-with-transformers.ipynb) for reference.

**Comment by SkalskiP** [comment]
> No worries. There is this [issue](https://github.com/roboflow/supervision/issues/1295) which requires work on obb. I have worked on obb before so should I try to work on this one?

@Bhavay-2001 I think we should finish work on https://github.com/roboflow/supervision/pull/1409 first.

**Pull request closed without merging**
