### PR TITLE
docs:  📝 update installation and source installation methods

### PR DESCRIPTION
**Pull request by onuralpszr**
# Description

This PR update readme.md installation sections for source and normal installation methods and also introduce poetry dev installation method as well. 

## Type of change

-   [X] This change requires a documentation update

## Docs

-   [X] Docs updated? What were the changes:

### CODE REVIEW

**Comment by onuralpszr** [comment]
@SkalskiP this is initial PR please check it out but I will do bit more changes before do finalize

**Comment by SkalskiP** [comment]
Hi, @onuralpszr 👋🏻! Awesome work 💪🏻 

It turned out to be a lot of important information. I don't want the `README.md` to be overly verbose. Let me move it to docs and refer it to `README.md`.

**Comment by SkalskiP** [comment]
@onuralpszr when I execute:

```bash
poetry install ".[desktop]"
```

I got this error:

```
No arguments expected for "install" command, got ".[desktop]"
```

Shouldn't we have this command here:

```bash
poetry install --extras "desktop"
```

**Comment by onuralpszr** [comment]
> @onuralpszr when I execute:
> 
> ```shell
> poetry install ".[desktop]"
> ```
> 
> I got this error:
> 
> ```
> No arguments expected for "install" command, got ".[desktop]"
> ```
> 
> Shouldn't we have this command here:
> 
> ```shell
> poetry install --extras "desktop"
> ```

Yes I fixed, I typed quickly forgot about that syntax

**Comment by SkalskiP** [comment]
@onuralpszr what do you think about it?

https://github.com/roboflow/supervision/assets/26109316/552b6a3f-9052-439c-a36e-dfefe6cf9392

**Comment by SkalskiP** [comment]
@onuralpszr question from my side is how do I install dev dependencies like `black` or `issort`?

**Comment by onuralpszr** [comment]
> @onuralpszr question from my side is how do I install dev dependencies like `black` or `issort`?

https://github.com/roboflow/supervision/pull/218 :)

**Comment by onuralpszr** [comment]
> @onuralpszr question from my side is how do I install dev dependencies like `black` or `issort`?

"poetry install" will install dev deps and usual deps unless we said otherwise since I also open new PR this will makes easier for that process as well.

**Comment by SkalskiP** [comment]
Oh... I don't want dev dependencies to be installed by default. Mainly I don't want them to be included in the production package.

**Comment by onuralpszr** [comment]
> Oh... I don't want dev dependencies to be installed by default. Mainly I don't want them to be included in the production package. 

That's only for poetry install not for prod

**Comment by SkalskiP** [comment]
> That's only for poetry install not for prod. Pip install will only bring main requirements not dev or docs

@onuralpszr no complains. Let's keep it that way and see how it goes.

**Pull request merged**
