### PR TITLE
feat(ByteTrack): Allow ByteTrack to track detection without class ids

### PR DESCRIPTION
**Pull request by Kadermiyanyedi**
**_Description:_**
This PR modifies ByteTrack to handle detections that do not include a class_id, improving the flexibility of the tracking algorithm. In cases where models don’t return a class_id, ByteTrack will now assign a default internal ID to ensure continued tracking.

**_Key Changes:_**
Default class_id Assignment:

- If class_id is missing from the detection, a default value of -5 is assigned to all detections.
- If class_id is available, the algorithm uses it as normal.

This ensures that ByteTrack works seamlessly with models that do not provide class_id, without breaking existing functionality.

You can test the functionality with the provided [Colab Notebook](https://colab.research.google.com/drive/1SXZndmumMotpHobM3kTefuv2pkggyy_R?usp=sharing) which demonstrates ByteTrack handling cases with and without class_id.

#1582

### CODE REVIEW

**Comment by LinasKo** [comment]
Hey @Kadermiyanyedi 👋 

Did you try checking what happens with the `class_id` after it's given to ByteTrack? I'm still super curious - maybe we can remove it altogether.

Is that something you'd have time for?

**Comment by LinasKo** [comment]
I suggested a special value other than `-1` myself, but it does feel a bit arbitrary.

However, I'll take an unconventional approach and merge the PR, in hopes of finding a way to remove the need for classes entirely. If that fails, I'll come back and change the special value to something else.

Thank you @Kadermiyanyedi! Expect to see this in the next supervision release 😉

**Review by LinasKo — APPROVED** [review]

**Comment by Kadermiyanyedi** [comment]
@LinasKo Hi, due to the busy schedule, I missed your comment on the PR and forgot to reply—sorry about that. I tested your suggestion and confirmed that class IDs are not necessary; it works without them. I’m opening a PR for this right away. Would it be possible to revert the PR we merged?

**Comment by LinasKo** [comment]
✅ Reverted

**Pull request merged**
