### PR TITLE
ci: 👷 pypi username - password swap with token

### PR DESCRIPTION
**Pull request by onuralpszr**
# Description

Pypi username / password has been replaced to with pypi token

### CODE REVIEW

**Comment by LinasKo** [comment]
As discussed privately, we'll instead set this up with Trusted Providers.

@onuralpszr , we now have the publishers set up on PyPi. We can proceed with changing the code.

**Comment by onuralpszr** [comment]
> As discussed privately, we'll instead set this up with Trusted Providers.
> 
> @onuralpszr , we now have the publishers set up on PyPi. We can proceed with changing the code.

Single file or double file ?

**Comment by LinasKo** [comment]
> Are we going to use single file or both files (change trigger control done via "release") ?

We've added 2 publishers. One for release via `publish.yml` and one for test, via `publish-test.yml`.

**Comment by LinasKo** [comment]
Why do both files have a "🚀 Publish to Test-PyPi" and "🚀 Publish to PyPi"? Should it not be one for each?

**Comment by onuralpszr** [comment]
> Why do both files have a "🚀 Publish to Test-PyPi" and "🚀 Publish to PyPi"? Should it not be one for each?

Current setup

pre-release versions goes to pypi and pypi-test server
release version goes to pypi and pypi-test server

**Comment by LinasKo** [comment]
So publish-test isn't actually for test, but for pre-release. Can we add a comment in the file? This isn't automatically obvious for someone new to the system.

**Review by LinasKo — APPROVED** [review]
Approving prremptively with small changes incoming as agreed in a separate conversation

**Pull request merged**
