### PR TITLE
Fix citation.cff file

### PR DESCRIPTION
**Pull request by capjamesg**
The current `CITATION.cff` file is not properly formatted, which means GitHub cannot parse it to create citations automatically in the `Cite this repository` section of the project:

Screenshot 2023-08-15 at 09 55 15

This PR fixes the issues present to create a valid `CITATION.cff` file.

### CODE REVIEW

**Comment by onuralpszr** [comment]
@capjamesg  could you switch to "develop" branch for merge because you are going to merge against "main"  and we don't PR to main directly plus I can fix citation.cff file problem on pre-commit side as well.

**Comment by capjamesg** [comment]
I have amended the PR target to `develop`.

**Review by onuralpszr — APPROVED** [review]
LGTM, Citation looks fine on your repo so I am merging. Thank you !!

**Comment by SkalskiP** [comment]
@capjamesg and @onuralpszr awesome! I know it is small PR, but I love seeing stuff like that happen autonomously. James noticed something wrong, and Onuralp made sure everything was done properly. 🔥

**Pull request merged**
