### PR TITLE
Detection encode decode string

### PR DESCRIPTION
**Pull request by hardikdava**
# Description

This can be very useful for json communication. Generally numpy array has to be encode for json communication. This functionality is very useful for REST api communication, MQTT, kafka communication. This implementation made this communication very simple by extending functionality of Detections class. 

## Type of change

-   [x] New feature (non-breaking change which adds functionality)
-   [x] This change requires a documentation update

## How has this change been tested, please provide a testcase or example of how you tested the change?

Tested locally. 

## Docs

-   [ ] Docs updated? What were the changes:

Test Script
```
import supervision as sv
import cv2


from ultralytics import YOLO


model = YOLO("yolov8s-seg.pt")


img_path = "path-to-your-image"

img = cv2.imread(img_path)
yolo_result = model.predict([img])[0]

# Simulate encode process from APP-1
detections = sv.Detections.from_yolov8(yolo_result)

# Test with empty Detections
# detections = sv.Detections.empty()

encoded_detections = detections.to_encoded_string()

# Assume encoded detections from APP-1
image_height, image_width, _ = img.shape

# Test with Masks
decoded_detections = sv.Detections.from_encoded_string(encoded_detections=encoded_detections, resolution_wh=(image_width, image_height))

# Test without Masks
# decoded_detections = sv.Detections.from_encoded_string(encoded_detections=encoded_detections)  # Only boxes

# Visualize
box_annotator = sv.BoxAnnotator()
mask_annotator = sv.MaskAnnotator()
labels = [f"{class_id}-{confidence}" for _, _, confidence, class_id, _ in decoded_detections]
render_img = box_annotator.annotate(scene=img, detections=decoded_detections, labels=labels)
render_img = mask_annotator.annotate(scene=img, detections=decoded_detections)
cv2.imshow("Result", render_img)
cv2.waitKey(0)

```

### CODE REVIEW

**Comment by SkalskiP** [comment]
Hi @hardikdava 👋🏻 I’m a bit worried about the efficiency of that solution. Primarily mask encoding and decoding. Did you measured how long it takes to do it?

**Comment by hardikdava** [comment]
@SkalskiP mask encoding decoding is not supported yet. But my plan is to convert masks into polygons and encode polygons. Once the polygons are decoded then it can be converted to mask using existing function. This is how it's done in various annotation plateforms.

**Comment by SkalskiP** [comment]
@hardikdava, that sounds much better. It seems it's a lot lighter operation.

**Comment by hardikdava** [comment]
@SkalskiP , I suggest to move `approximate_polygon` function from `dataset/utils.py` to `detections/utils.py`. I got an error of `circular import` when I want to use this function in `detections/core.py`. Anyhow this function is related to detections processing, so it should belongs to detection utils. What do you think about it?

**Comment by SkalskiP** [comment]
@hardikdava feel free to move it in your PR

**Comment by hardikdava** [comment]
Hi @SkalskiP , this PR is ready for test. Please find test script in the description. I have added comment for different tests like empty detections, with only boxes, full tests. Let me know if it needed any fixes.

**Pull request closed without merging**
