### PR TITLE
Create PercentageBoxAnnotator Class

### PR DESCRIPTION
**Pull request by xaristeidou**
# Description

Created PercentageBoxAnnotator Class.

Screenshot from 2023-10-13 14-56-55

Link to video demo: https://drive.google.com/file/d/14wkO9FVAjxJd8QHVMwknuKhRASwrMPJp/view?usp=drive_link

List any dependencies that are required for this change.

## Type of change

Please delete options that are not relevant.

-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] This change requires a documentation update

## How has this change been tested, please provide a testcase or example of how you tested the change?

Tested on video sample using YOLOv8 results -> reformed to Detections -> input to sv.PercentageBoxAnnotator()

## Any specific deployment considerations

New annotation feature

## Docs

-   [ ] Docs updated? What were the changes:

### CODE REVIEW

**Comment by onuralpszr** [comment]
@xaristeidou  you revert a code in color section  and that make test fails because of import problem.

**Comment by xaristeidou** [comment]
@onuralpszr Did something change in color imports?
 
These are import now(left) from fresh git clone, and on right what i was working on

Screenshot from 2023-10-13 19-26-30

**Comment by onuralpszr** [comment]
https://github.com/roboflow/supervision/pull/465

**Comment by xaristeidou** [comment]
Ok will update a bit later when back to office

**Pull request closed without merging**
