### PR TITLE
merge `supervision-0.25.1` hot fix into `main` before `supervision-0.26.0` release

### PR DESCRIPTION
**Pull request by SkalskiP**
# Description

Merge numpy hotfix for poetry installations.

### CODE REVIEW

**Comment by onuralpszr** [comment]
This change already exist in development

**Comment by SkalskiP** [comment]
@onuralpszr creating PR from `develop` to `main` was not possible as it was not up to date

**Comment by onuralpszr** [comment]
> @onuralpszr creating PR from `develop` to `main` was not possible as it was not up to date

Okay, sure

**Comment by onuralpszr** [comment]
> @onuralpszr, can you approve?

All good after merge, thank you.

**Pull request merged**
