### PR TITLE
Add Support for Center Left,Right Text Position for LabelAnnotator

### PR DESCRIPTION
**Pull request by sansyo**
Added Position.CENTER_LEFT
Description:
Summary
This Pull Request introduces support for the CENTER_LEFT text position in the LabelAnnotator class. Previously, the resolve_text_background_xyxy method did not handle CENTER_LEFT, resulting in a None return value and potentially causing errors during annotation tasks.

Changes
Added an additional condition to the resolve_text_background_xyxy method to handle CENTER_LEFT text positioning. This ensures that when CENTER_LEFT is specified as the text position, the method calculates and returns the correct coordinates for the text background.
Included error handling for unsupported text positions to improve code robustness and provide clearer feedback for developers.
Impact
Enhanced Functionality: The LabelAnnotator class can now correctly handle CENTER_LEFT text positioning, allowing for more flexibility in text annotation tasks.
Improved Robustness: By adding explicit handling for unsupported text positions, the updated method prevents ambiguous behaviors and assists in debugging.
Rationale
The addition of CENTER_LEFT support addresses a specific need for more detailed control over text positioning in image annotations, especially in cases where text needs to be closely aligned to the left of a central anchor point while maintaining vertical center alignment.

Testing
Changes have been locally tested with various scenarios including different text positions to ensure that the new CENTER_LEFT handling works as expected and does not adversely affect the existing functionality.

I look forward to your feedback and any further suggestions for improvement.

### CODE REVIEW

**Comment by onuralpszr** [comment]
@sansyo hello could you please fix your "indent" problem and also accept CLA too. Also add CENTER_RIGHT too plus share small collab and pictures for how is it looks like as well.

**Comment by sansyo** [comment]
@onuralpszr 
hello. 
I fixed that wrong indent and added CENTER_RIGHT.

here is my result of colab notebook and result images.
looks like something wrong with my modification about CENTER_RIGHT with wrong textbox drawing.

CENTER
LEFT
RIGHT


https://colab.research.google.com/drive/1MuERFL0ifmLiVI5skgHBRXGpmt8IQGAD?usp=sharing
https://github.com/sansyo/supervision/commit/118ce7daa3cc0e4a105b09cbb2aa310f7e499195

**Comment by onuralpszr** [comment]
@sansyo I checked RIGHT side and render correctly at my end. 

image

image

**Comment by sansyo** [comment]
@onuralpszr 
thank you for your check of RIGHT side.
I reran the program and somehow got same result as you and different from my previous result.(´・ω・｀)

RIGHT2

**Comment by onuralpszr** [comment]
@sansyo  LGTM !!, Thank you. I am merging in :) 

> @onuralpszr thank you for your check of RIGHT side. I reran the program and somehow got same result as you and different from my previous result.(´・ω・｀)
> 
> RIGHT2

Awesome !! :)

**Review by onuralpszr — APPROVED** [review]

**Pull request merged**
