### PR TITLE
fix(examples): 🐞 tracking LabelAnnotator and traffic_analysis deps fixed

### PR DESCRIPTION
**Pull request by onuralpszr**
### Description

- [X] tracking LabelAnnotator classes removed 
- [X] traffic_analysis deps fixed

### CODE REVIEW

**Comment by SkalskiP** [comment]
Hi, @onuralpszr! 👋🏻 Have you had a chance to test the demo notebook or traffic analysis example?

**Comment by onuralpszr** [comment]
Yes it works

**Comment by SkalskiP** [comment]
Awesome. Do we want to include this in the possible `supervision-0.17.1` release? Or wait till `supervision-0.18.0`.

**Comment by SkalskiP** [comment]
Awesome, let's merge it now.

**Pull request merged**
