### PR TITLE
Ignore Empty Newlines in Yolo Label File

### PR DESCRIPTION
**Pull request by SummitStudiosDev**
# Description

I had an empty newline after the label in one of my yolo label files, it started broke the entire program, failing to load the dataset.
```Traceback (most recent call last):
  File "C:\Users\codys\Desktop\project\labelled datasets\visualizelabel - toFile.py", line 19, in <module>
    dataset = sv.DetectionDataset.from_yolo(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\codys\AppData\Local\Programs\Python\Python311\Lib\site-packages\supervision\dataset\core.py", line 313, in from_yolo
    classes, images, annotations = load_yolo_annotations(
                                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\codys\AppData\Local\Programs\Python\Python311\Lib\site-packages\supervision\dataset\formats\yolo.py", line 161, in load_yolo_annotations
    annotation = yolo_annotations_to_detections(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\codys\AppData\Local\Programs\Python\Python311\Lib\site-packages\supervision\dataset\formats\yolo.py", line 85, in yolo_annotations_to_detections
    class_id.append(int(values[0]))
                        ~~~~~~^^^
IndexError: list index out of range
```
I went to yolo.py and I added a line printing out values, and it gave me `[]` as causing the problem, which makes sense.
I then went and added a line printing `print(lines)` (because `values = line.split()` and `for line in lines:`), and I got 
```
['1 0.35195 0.51250 0.16016 0.11112', '']
['1 0.35195 0.51250 0.16016 0.11112', '']
``` 
preceding the error message which led me to conclude that there must be an extra newline. 

Adding a check to see if values is length 0, and if it is just run a continue statement solves the problem and the library simply ignores the empty line instead of throwing an error. 
```
if(len(values)==0):
            continue
```

## Type of change
-   [x] Bug fix (non-breaking change which fixes an issue)

## How has this change been tested, please provide a testcase or example of how you tested the change?

My program now runs, and I didn't have to modify my label txts at all.

## Any specific deployment considerations

This would be a rather harmless ease-of-convivence fix, as all it does is ignore empty Newlines in a yolo label file, which otherwise would crash the entire program.

This is my first pull request so sorry if it's confusing!

### CODE REVIEW

**Comment by SkalskiP** [comment]
Hi, @SummitStudiosDev! 👋🏻 Thanks a lot for your interest in our project. I moved the solution into `read_txt_file` to make it more reusable. 

@onuralpszr I tried to exclude `test/utils/test_file.py` from `W291`. What am I doing wrong?

**Comment by onuralpszr** [comment]
> Hi, @SummitStudiosDev! 👋🏻 Thanks a lot for your interest in our project. I moved the solution into `read_txt_file` to make it more reusable.
> 
> @onuralpszr I tried to exclude `test/utils/test_file.py` from `W291`. What am I doing wrong?



> Hi, @SummitStudiosDev! 👋🏻 Thanks a lot for your interest in our project. I moved the solution into `read_txt_file` to make it more reusable.
> 
> @onuralpszr I tried to exclude `test/utils/test_file.py` from `W291`. What am I doing wrong?

exclude not needed and fixed.

**Comment by SkalskiP** [comment]
@onuralpszr, you didn't fix the test. The test was broken by auto-format. All you did was change the expected result to match the test broken by autoformat.

**Comment by SkalskiP** [comment]
Thanks a lot for your help, @SummitStudiosDev 🙏🏻 Let's merge this. I will solve test problems on my own.

**Review by SkalskiP — APPROVED** [review]

**Pull request merged**
