### PR TITLE
Update annotators.md

### PR DESCRIPTION
**Pull request by josephofiowa**
included description of what annotators are; clarified how to use the visualization widget

# Description

Updated the supervision annotators docs page to provide clarity on what annotators do and how to use a custom annotator visualizer.

## Type of change

Please delete options that are not relevant.

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ x ] This change requires a documentation update

## How has this change been tested, please provide a testcase or example of how you tested the change?

Yes, docs load.

## Any specific deployment considerations

No deployment changes to consider; only edited markdown file

## Docs

-   [ X ] Docs updated? What were the changes:

The `annotators.md` file includes a description of what annotators do.

### CODE REVIEW

**Review by joaomarcoscrs — APPROVED** [review]
Excellent clarification here!

**Comment by LinasKo** [comment]
Hi @josephofiowa, I suggest leaving the docs as they were.

Let's keep the UI short and concise, and as soon as we see confusion - then add more explanation.

**Review by LinasKo — APPROVED** [review]

**Comment by josephofiowa** [comment]
@LinasKo based on your feedback in supervision slack, I left the short two-liner of "what are annotators" at the top:
> Annotators accept detections and apply box or mask visualizations to the detections. Annotators have many available styles.

And made the second description of trying out annotators on COCO more concise:
> Visualize annotators on images with COCO classes such as people, vehicles, animals, household items.

**Comment by LinasKo** [comment]
Following our discussion, sure - let's include a bit of explanation for what the annotators do. Merging!

**Pull request merged**
