### PR TITLE
docs: 📝 code of conduct added

### PR DESCRIPTION
**Pull request by onuralpszr**
# Description

Code of conduct based on : https://www.contributor-covenant.org/ 
Original URL : https://www.contributor-covenant.org/version/2/1/code_of_conduct/code_of_conduct.md

## Docs

-   [X] Docs updated? What were the changes: CoC added

### CODE REVIEW

**Comment by SkalskiP** [comment]
@capjamesg it would be excellent if you could take a look. Do we need to add anything more?

**Comment by capjamesg** [comment]
Thank you for submitting this PR, @onuralpszr.

I am in full support of having a Code of Conduct (CoC). Codes of conduct are an important part of welcoming people into a community: with a CoC, people know there is recourse should they encounter any behavior that violates the CoC. At all times, we should be striving to create an inclusive environment for everyone nterested in contributing to `supervision`.

Before we merge this, _all_ maintainers should weigh in with any feedback on the CoC and whether any changes should be made to tailor it to our community.

CoCs are living documents that we must all know, practice, and refer to in our work as maintainers. If violations of the CoC are spotted, maintainers must flag them as soon as possible to a member of the Roboflow team for review.

I am willing to help with CoC enforcement and monitor an official, anonymous system through which people can flag behaviour for review. @SkalskiP your help here would be appreciated, too.

**Comment by SkalskiP** [comment]
@capjamesg 

> CoCs are living documents that we must all know, practice, and refer to in our work as maintainers.

Fully agree! This version of CoC is a good one to start with. We will update and improve it over time just as we do the guidelines for contributors.

> If violations of the CoC are spotted, maintainers must flag them as soon as possible to a member of the Roboflow team for review.

Let's create a mechanism for people to report violations. An e-mail address they can write to? Or a topic in the discussion tab?

> SkalskiP your help here would be appreciated, too.

I'm in! I want supervision to be a place where all people can contribute. Friendly and helpful.

Meanwhile, I think this version of the CoC is good enough to merge.

**Review by SkalskiP — APPROVED** [review]

**Comment by capjamesg** [comment]
This wasn't ready to merge. There is a [placeholder in the document](https://github.com/roboflow/supervision/pull/384/files#diff-ffdbe3a1e7ee93cacfc080b6c635ccf3a8f6b0f00f2fb884f78c6b5f9dac8fd2R64).

> Let's create a mechanism for people to report violations. An e-mail address they can write to? Or a topic in the discussion tab?

Working on this now.

**Comment by SkalskiP** [comment]
@capjamesg Oh, sorry forgot about that. Would you be so kind as to create a new PR once you set up the mail?

**Comment by capjamesg** [comment]
Will do!

**Pull request merged**
